# -*- coding: utf-8 -*-
"""Cria campo_sistema (registro unico e estavel de todo campo de preenchimento/insercao de
dados das Telas 1 a 7, Id no formato T(tela)(sequencial) -- ver backend/models.py:CampoSistema)
e as 3 colunas novas em id_comercial (campo_id, centro_custo_padrao_codigo,
fator_venda_padrao_id) que ligam cada no folha da arvore de Ids Comerciais ao campo de origem e
aos padroes de Centro de Custo / Fator de Venda. Idempotente -- repopula campo_sistema do zero
a cada rodada (e so leitura/referencia, nunca editado por usuario)."""
import sqlite3
from backend.database import DB_PATH, engine
from backend import models as m

SEED = [
    ('T11', 1, 'Código Projeto', 'p_codigo_projeto', 0),
    ('T12', 1, 'Data', 'p_data', 1),
    ('T13', 1, 'Cliente', 'p_cliente', 2),
    ('T14', 1, 'Cidade de Instalação', 'p_cidade_instalacao', 3),
    ('T15', 1, 'Estado', 'p_estado_uf', 4),
    ('T16', 1, 'Altitude da Instalação (m)', 'p_altitude_m', 5),
    ('T17', 1, 'Estação Climatológica (INMET)', 'p_estacao_busca', 6),
    ('T18', 1, 'Temperatura Ambiente (°C)', 'p_temp_ambiente', 7),
    ('T19', 1, 'UR Externa (%)', 'p_ur_externa', 8),
    ('T110', 1, 'Contato', 'p_contato', 9),
    ('T111', 1, 'Telefone', 'p_telefone', 10),
    ('T112', 1, 'Tipo de Comando', 'p_tipo_comando', 11),
    ('T113', 1, 'Tensão Elétrica dos Equipamentos', 'p_tensao_equipamentos', 12),
    ('T114', 1, 'Tensão Elétrica de Comando', 'p_tensao_comando', 13),
    ('T115', 1, 'Custo de Energia (R$/kWh)', 'p_custo_energia', 14),
    ('T116', 1, 'Pasta de Salvamento do Projeto', 'p_pasta_salvamento', 15),
    ('T117', 1, 'Condição do Salão de Vendas', 'p_condicao_salao', 16),
    ('T118', 1, 'Considerar Iluminação Ambiente', 'p_considerar_iluminacao_ambiente', 17),
    ('T119', 1, 'Nome', 'sNome', 18),
    ('T120', 1, 'Gás Refrigerante', 'sGas', 19),
    ('T121', 1, 'Válvula de Expansão', 'sExp', 20),
    ('T122', 1, 'Fabricante Válvula', 'sFabricanteValvula', 21),
    ('T123', 1, 'Temp. Evaporação (°C)', 'sTempEvap', 22),
    ('T124', 1, 'Custo Sistema Simples (R$)', 'sCustoSistemaSimples', 23),
    ('T125', 1, 'Custo Sistema Projeto (R$)', 'sCustoSistemaProjeto', 24),
    ('T126', 1, 'Nº de Degelos/Dia', 'sQuantidadeDegeloDia', 25),
    ('T127', 1, 'Tempo de Degelo por Ciclo (min)', 'sTempoDegeloMin', 26),
    ('T128', 1, 'Tipo Automação Linhas', 'sTipoAutomacaoLinhas', 27),
    ('T129', 1, 'Fornecedor Automação Linhas', 'sAutomacaoLinhasFabricante', 28),
    ('T130', 1, 'Tipo de Equipamento Compressão', 'sTipoCompressao', 29),
    ('T131', 1, 'Estrutura', 'sEstruturaCompressao', 30),
    ('T132', 6, 'Seleção Condensador a Ar', 'sSelecaoCondensadorAr', 31),
    ('T133', 6, 'Delta de Condensação (°C)', 'sDeltaCondensacao', 32),
    ('T134', 1, 'Tipo de Partida - Compressores', 'sPartida', 33),
    ('T135', 1, 'Modo Operação - Compressores', 'sModoOperacao', 34),
    ('T136', 1, 'Tipo Automação Equipamentos', 'sAutomacao', 35),
    ('T137', 1, 'Fornecedor Automação Equipamentos', 'sAutomacaoFabricante', 36),
    ('T138', 1, 'Linha de Líquido — Temp. após Sub-resfriamento (°C)', 'sTempAposSubresfriamento', 37),
    ('T139', 1, 'Forçadores', 'p_fab_global_forcador', 38),
    ('T140', 1, 'Unidades Condensadoras', 'p_fab_global_uc', 39),
    ('T141', 1, 'Condensadores', 'p_fab_global_condensador', 40),
    ('T21', 2, 'Nome da Câmara', 'c2_nome', 41),
    ('T22', 2, 'Sistema (vínculo Tela 1)', 'c2_sistema_id', 42),
    ('T23', 2, 'Linha de Sucção', 'c2_linha_succao', 43),
    ('T24', 2, 'Linha Elétrica', 'c2_linha_eletrica', 44),
    ('T25', 2, 'Temp. Interna (°C)', 'c2_temp_interna', 45),
    ('T26', 2, 'Utilizar Válv. Reg. de Pressão?', 'c2_utilizar_valv_reg_pressao', 46),
    ('T27', 2, 'Dt. Evaporação Desejado (°C)', 'c2_dt_evaporacao_desejado', 47),
    ('T28', 2, 'Largura (m)', 'c2_largura', 48),
    ('T29', 2, 'Comprimento (m)', 'c2_comprimento', 49),
    ('T210', 2, 'Pé-Direito (m)', 'c2_pedireito', 50),
    ('T211', 2, 'Produto Estocado', 'c2_produto_id', 51),
    ('T212', 2, 'Qtd. Estocada (kg)', 'c2_qtd_estocada', 52),
    ('T213', 2, 'Movim. Diária (kg/24h)', 'c2_mov_diaria', 53),
    ('T214', 2, 'Tempo de Processo (h)', 'c2_tempo_processo', 54),
    ('T215', 2, 'Temp. Entrada (°C)', 'c2_temp_entrada', 55),
    ('T216', 2, 'Temp. Saída (°C)', 'c2_temp_saida', 56),
    ('T217', 2, 'Tipo de Embalagem', 'c2_tipo_embalagem_id', 57),
    ('T218', 2, 'Massa de Embalagem (kg/24h)', 'c2_massa_embalagem', 58),
    ('T219', 2, 'Isolamento Parede', 'c2_isolamento_parede_id', 59),
    ('T220', 2, 'Isolamento Teto', 'c2_isolamento_teto_id', 60),
    ('T221', 2, 'Isolamento Piso', 'c2_isolamento_piso_id', 61),
    ('T222', 2, 'Fonte do ar das paredes', 'c2_fonte_ar', 62),
    ('T223', 2, 'Temp. Adjacente Paredes (°C)', 'c2_temp_adjacente', 63),
    ('T224', 2, 'Umidade Adjacente Paredes (%)', 'c2_umidade_adjacente', 64),
    ('T225', 2, 'Qtd', 'c2_pt_qtd', 65),
    ('T226', 2, 'Largura (m)', 'c2_pt_larg', 66),
    ('T227', 2, 'Altura (m)', 'c2_pt_alt', 67),
    ('T228', 2, 'Abertura (min/h)', 'c2_pt_freq', 68),
    ('T229', 2, 'Proteção', 'c2_pt_protecao', 69),
    ('T230', 2, 'Fonte do ar', 'c2_pt_fonte', 70),
    ('T231', 2, 'Temp. Adjacente da porta (°C)', 'c2_pt_temp', 71),
    ('T232', 2, 'Umidade Adjacente da porta (%)', 'c2_pt_ur', 72),
    ('T233', 2, 'Nº Pessoas', 'c2_num_pessoas', 73),
    ('T234', 2, 'Tempo (h/24h)', 'c2_tempo_pessoas', 74),
    ('T235', 2, 'Qtd. Luminárias', 'c2_qtd_luminarias', 75),
    ('T236', 2, 'Horas Iluminação/Dia (carga)', 'c2_horas_iluminacao_carga', 77),
    ('T237', 2, 'Tipo (catálogo)', 'c2_eqTipo', 78),
    ('T238', 2, 'Qtd.', 'c2_eqQtd', 79),
    ('T239', 2, 'Tempo (h/24h)', 'c2_eqTempo', 80),
    ('T240', 2, 'Fator de Segurança (%)', 'c2_fator_seguranca', 81),
    ('T241', 2, 'Tempo Func. Compressores (h/24h)', 'c2_tempo_func_compressores', 82),
    ('T242', 2, 'Fabricante', 'c2_evFab', 83),
    ('T243', 2, 'Linha', 'c2_evLinha', 84),
    ('T31', 3, 'Nome da Câmara', 'c3_nome', 85),
    ('T32', 3, 'Sistema (vínculo Tela 1)', 'c3_sistema_id', 86),
    ('T33', 3, 'Linha de Sucção', 'c3_linha_succao', 87),
    ('T34', 3, 'Linha Elétrica', 'c3_linha_eletrica', 88),
    ('T35', 3, 'Tipo', 'c3_tabela02_id', 89),
    ('T36', 3, 'Área (m²)', 'c3_area', 90),
    ('T37', 3, 'Pé-Direito (m)', 'c3_pedireito', 91),
    ('T38', 3, 'Temp. Interna (°C)', 'c3_temp_interna', 92),
    ('T39', 3, 'Utilizar Válv. Reg. de Pressão?', 'c3_utilizar_valv_reg_pressao', 93),
    ('T310', 3, 'Dt. Evaporação Desejado (°C)', 'c3_dt_evaporacao_desejado', 94),
    ('T311', 3, 'Nº de Portas', 'c3_num_portas', 95),
    ('T312', 3, 'Largura do Vão (m)', 'c3_porta_largura', 96),
    ('T313', 3, 'Altura do Vão (m)', 'c3_porta_altura', 97),
    ('T314', 3, 'Fator de Segurança (%)', 'c3_fator_seguranca', 98),
    ('T315', 3, 'Fabricante', 'c3_evFab', 99),
    ('T316', 3, 'Linha', 'c3_evLinha', 100),
    ('T41', 4, 'Sistema (vínculo Tela 1)', 'c4_sistema_id', 101),
    ('T42', 4, 'Linha de Sucção', 'c4_linha_succao', 102),
    ('T43', 4, 'Linha Elétrica', 'c4_linha_eletrica', 103),
    ('T44', 4, 'Setor', 'c4_setor_id', 104),
    ('T45', 4, 'Banco de Dados', 'c4_banco_id', 105),
    ('T46', 4, 'Modelo', 'c4_modelo_expositor_id', 106),
    ('T47', 4, 'Comprimento do Módulo (m)', 'c4_modCompr', 107),
    ('T48', 4, 'Quantidade', 'c4_modQtd', 108),
    ('T51', 5, 'Fator de Potência', 't5_fatorPotencia', 109),
    ('T52', 5, 'Fonte Tensão Quadro de Linhas', 't5_quadroTensaoFonte', 110),
    ('T53', 5, 'Observações Técnicas', 't5_observacao', 111),
    ('T61', 6, 'Sistema (Rack Paralelo)', 't11_sistema_id', 112),
    ('T62', 6, 'Fabricante Compressor', 't11_fabricante_compressor', 113),
    ('T63', 6, 'Linha Compressor', 't11_linha_compressor', 114),
    ('T64', 6, 'Quantidade de Compressores/Rack', 't11_quantidade_compressores', 115),
    ('T65', 6, 'Folga Técnica (%)', 't11_folga_tecnica_pct', 116),
    ('T66', 6, 'Tipo Motor Compress.', 't11_filtro_motor_compressor', 117),
    ('T67', 6, 'Fabricante Condensador', 't11_cond_fabricante', 118),
    ('T68', 6, 'Linha Condensador', 't11_cond_linha', 119),
    ('T69', 6, 'Tipo Condensador', 't11_cond_tipoCondensador', 120),
    ('T610', 6, 'Tipo de Motor', 't11_cond_polos', 121),
    ('T611', 6, 'Aletas por Polegada (FPI)', 't11_cond_fpi', 122),
    ('T612', 6, 'Proteção de Aletas', 't11_cond_protecaoAletas', 123),
    ('T613', 6, 'Folga Condensador (%)', 't11_cond_folga', 124),
    ('T614', 6, 'Quantidade de Condensadores', 't11_cond_qtdCondensadores', 125),
    ('T615', 6, 'Notas', 't11_cond_notas', 126),
    ('T71', 7, 'Largura da Placa (Parede/Teto) (m)', 't10_largPlaca', 127),
    ('T72', 7, 'Largura da Placa de Piso (m)', 't10_pisoLarg', 128),
    ('T73', 7, 'Comprimento da Placa de Piso (m)', 't10_pisoComp', 129),
    ('T74', 7, 'Largura Mín. de Aproveitamento (m)', 't10_larguraMinAprov', 130),
    ('T244', 2, 'Portas — Qtd', 'porta_quantidade', 131),
    ('T245', 2, 'Portas — Largura (m)', 'porta_largura', 132),
    ('T246', 2, 'Portas — Altura (m)', 'porta_altura', 133),
    ('T247', 2, 'Portas — Abertura (min/h)', 'porta_freq_abertura_min_h', 134),
    ('T248', 2, 'Portas — Proteção', 'porta_protecao', 135),
    ('T249', 2, 'Portas — Fonte do ar', 'porta_fonte_ar', 136),
    ('T250', 2, 'Portas — Temp. Adjacente (°C)', 'porta_temp_adjacente', 137),
    ('T251', 2, 'Portas — Umidade Adjacente (%)', 'porta_umidade_adjacente', 138),
    ('T252', 2, 'Forçadores — Folga Desejada (%)', 'forcador_folga', 139),
    ('T253', 2, 'Forçadores — Qtd.', 'forcador_quantidade', 140),
    ('T254', 2, 'Forçadores — Considerar', 'forcador_considerar', 141),
    ('T255', 2, 'Forçadores — Tipo de Degelo', 'forcador_tipo_degelo', 142),
    ('T256', 2, 'Válvula — Modelo', 'valvula_modelo', 143),
    ('T257', 2, 'Válvula — Orifício', 'valvula_orificio', 144),
    ('T258', 2, 'Válvula — Capacidade Unit. (kcal/h)', 'valvula_capacidade', 145),
    ('T259', 2, 'Válvula — Conexão Entrada', 'valvula_entrada', 146),
    ('T260', 2, 'Válvula — Conexão Saída', 'valvula_saida', 147),
    ('T261', 2, 'Válvula — Tensão', 'valvula_tensao', 148),
    ('T262', 2, 'Válvula — Tipo (motor)', 'valvula_tipomotor', 149),
    ('T263', 2, 'Válvula — Controlador', 'valvula_controlador', 150),
    ('T317', 3, 'Forçadores — Folga Desejada (%)', 'forcador_folga', 151),
    ('T318', 3, 'Forçadores — Qtd.', 'forcador_quantidade', 152),
    ('T319', 3, 'Forçadores — Considerar', 'forcador_considerar', 153),
    ('T320', 3, 'Forçadores — Tipo de Degelo', 'forcador_tipo_degelo', 154),
    ('T321', 3, 'Válvula — Modelo', 'valvula_modelo', 155),
    ('T322', 3, 'Válvula — Orifício', 'valvula_orificio', 156),
    ('T323', 3, 'Válvula — Capacidade Unit. (kcal/h)', 'valvula_capacidade', 157),
    ('T324', 3, 'Válvula — Conexão Entrada', 'valvula_entrada', 158),
    ('T325', 3, 'Válvula — Conexão Saída', 'valvula_saida', 159),
    ('T326', 3, 'Válvula — Tensão', 'valvula_tensao', 160),
    ('T327', 3, 'Válvula — Tipo (motor)', 'valvula_tipomotor', 161),
    ('T328', 3, 'Válvula — Controlador', 'valvula_controlador', 162),
    ('T616', 6, 'Materiais Rack — Modelo', 'mat_modelo', 163),
    ('T617', 6, 'Materiais Rack — Quantidade', 'mat_qtd', 164),
    ('T142', 1, 'Modelo Controlador Linhas', 'sModeloControladorLinhas', 182),
    ('T143', 1, 'Modelo Controlador Equipamentos', 'sModeloControladorEquipamentos', 183),
    ('T264', 2, 'Iluminação — Tipo Ambiente', 'c2_tipo_ambiente_lumino_id', 184),
    ('T265', 2, 'Iluminação — Modelo Luminária', 'c2_modelo_luminaria_texto', 185),
    ('T266', 2, 'Iluminação — Potência/Luminária (W)', 'c2_potencia_luminaria_texto', 192),
    ('T329', 3, 'Largura (m)', 'c3_largura', 186),
    ('T330', 3, 'Comprimento (m)', 'c3_comprimento', 187),
    ('T331', 3, 'Iluminação — Qtd. Luminárias', 'c3_qtd_luminarias', 188),
    ('T332', 3, 'Iluminação — Tipo Ambiente', 'c3_tipo_ambiente_lumino_id', 189),
    ('T333', 3, 'Iluminação — Horas Iluminação/Dia (carga)', 'c3_horas_iluminacao_carga', 190),
    ('T334', 3, 'Iluminação — Modelo Luminária', 'c3_modelo_luminaria_texto', 191),
    ('T335', 3, 'Iluminação — Potência/Luminária (W)', 'c3_potencia_luminaria_texto', 193),
    ('T75', 7, 'Painéis — Câmara', 'painel_camara', 165),
    ('T76', 7, 'Painéis — Nome do Ambiente (se não climatizado)', 'painel_ambiente_nome', 166),
    ('T77', 7, 'Painéis — Tipo', 'painel_tipo', 167),
    ('T78', 7, 'Painéis — Espessura', 'painel_espessura', 168),
    ('T79', 7, 'Painéis — Perímetro/Largura (m)', 'painel_dimensao_1', 169),
    ('T710', 7, 'Painéis — Altura/Comprimento (m)', 'painel_dimensao_2', 170),
    ('T711', 7, 'Portas — Câmara', 'porta_camara', 171),
    ('T712', 7, 'Portas — Nome do Ambiente (se não climatizado)', 'porta_ambiente_nome', 172),
    ('T713', 7, 'Portas — Função', 'porta_funcao', 173),
    ('T714', 7, 'Portas — Modelo', 'porta_modelo', 174),
    ('T715', 7, 'Portas — Sentido', 'porta_sentido', 175),
    ('T716', 7, 'Portas — Vão Largura (mm)', 'porta_vao_largura_mm', 176),
    ('T717', 7, 'Portas — Vão Altura (mm)', 'porta_vao_altura_mm', 177),
    ('T718', 7, 'Portas — Fixação', 'porta_fixacao', 178),
    ('T719', 7, 'Portas — Esp. Fixação (mm)', 'porta_espessura_fixacao_mm', 179),
    ('T720', 7, 'Portas — Tensão', 'porta_tensao', 180),
    ('T721', 7, 'Portas — Observações', 'porta_observacoes', 181),
]


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    cols = [r[1] for r in cur.execute("PRAGMA table_info(id_comercial)").fetchall()]
    for coluna, tipo in (("campo_id", "TEXT"), ("centro_custo_padrao_codigo", "TEXT"), ("fator_venda_padrao_id", "INTEGER")):
        if coluna not in cols:
            cur.execute(f"ALTER TABLE id_comercial ADD COLUMN {coluna} {tipo}")
            print(f"Coluna id_comercial.{coluna} adicionada.")
        else:
            print(f"Coluna id_comercial.{coluna} ja existe.")
    conn.commit()
    conn.close()

    m.Base.metadata.create_all(bind=engine, tables=[m.CampoSistema.__table__])

    from backend.database import SessionLocal
    db = SessionLocal()
    db.query(m.CampoSistema).delete()
    for campo_id, tela, rotulo, seletor_html, ordem in SEED:
        db.add(m.CampoSistema(campo_id=campo_id, tela=tela, rotulo=rotulo,
                               seletor_html=seletor_html, ordem=ordem))
    db.commit()
    total = db.query(m.CampoSistema).count()
    db.close()
    print(f"{total} campos registrados em campo_sistema.")


if __name__ == "__main__":
    main()
