-- configuracao_global — bloco 1 de 1 (13 registros no total)

INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (3, 'potencia_dreno_wm', 150.0, 'Potência da resistência de dreno (W/m) — aparece na Compilação (Res. Dreno)', TRUE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (4, 'potencia_portas_wm', 150.0, 'Potência da resistência de portas (W/m) — multiplicado pelo perímetro do vão (2×altura + 2×largura) de cada câmara. Aparece na Compilação (Res. Portas)', TRUE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (5, 'comprimento_dreno_m', 10.0, 'Comprimento de resistência de dreno considerado por evaporador (m)', TRUE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (6, 'limite_valvula_equalizacao_m3', 2000.0, 'Volume de câmara (m³) por válvula de equalização de pressão', FALSE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (7, 'iluminacao_simples_w_m2', 250.0, 'Iluminação Câmara Simples — Potência de referência (W/m²), usada na Potência Ilum.', TRUE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (8, 'iluminacao_simples_lm_m2', 2400.0, 'Iluminação Câmara Simples — Iluminância de referência (lm/m², nível de lux do projeto luminotécnico), usada na Potência Ilum.', TRUE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (9, 'iluminacao_simples_potencia_lampada_w', 36.0, 'Iluminação Câmara Simples — Potência de uma lâmpada de referência (W), usada na Potência Ilum.', TRUE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (10, 'reducao_eev_pct', 20.0, 'Redução de consumo do compressor por Válvula de Expansão Eletrônica (%) — global, único para todo o app (não varia por sistema)', FALSE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (11, 'reducao_controle_capacidade_pct', 15.0, 'Redução MÁXIMA de consumo do compressor por Controle de Capacidade (descarregamento mecânico de cilindros — Modo Operação), aplicada quando o Sistema opera no piso de 35% de carga — decresce linearmente até 0% em 100% de carga. Faixa típica de literatura (descarregamento mecânico vs. liga-desliga): 15%-20% — ver calculo_consumo.py', FALSE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (12, 'reducao_inversor_pct', 30.0, 'Redução MÁXIMA de consumo do compressor por Inversor de Frequência (VFD — Modo Operação), aplicada quando o Sistema opera no piso de 20% de carga — decresce linearmente até 0% em 100% de carga. Faixa típica de literatura (VFD vs. liga-desliga, ganho de IEER): 30%-50% — ver calculo_consumo.py', FALSE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (13, 'reducao_ec_condensador_pct', 30.0, 'Redução MÁXIMA de consumo do ventilador do Condensador Remoto (Rack Paralelo, Tela 6) quando o modelo escolhido tem motor EC, aplicada quando o condensador opera no piso de 20% de carga (mesma folga de referência do Inversor de Frequência, tecnologia equivalente) — decresce linearmente até 0% em 100% de carga. Faixa típica de literatura (EC vs. motor AC de rotação fixa, ventiladores de condensador): 30%-50% — ver calculo_consumo.py', FALSE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (14, 'disjuntor_limite_curva_c_a', 80.0, 'Corrente nominal (A) até a qual o disjuntor usa Curva C — acima disso, Curva D (Tela 5 - Tabela de Disjuntores). Do cabeçalho da planilha original.', FALSE);
INSERT INTO "configuracao_global" ("id", "chave", "valor", "descricao", "pendente_confirmacao") VALUES (15, 'Folga Corrente Disjuntores', 5.0, 'Folga adotada sobre a corrente nominal ao escolher o disjuntor (Tela 5 - Tabela de Disjuntores), em %. Do cabeçalho da planilha original (0,05 = 5%).', FALSE);