-- campo_catalogo_opcao — bloco 1 de 1 (662 registros no total)

INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (107, 25, 'Natural', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (108, 25, 'Elétrico', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (109, 26, '220V-1F 50-60Hz', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (110, 27, '4,3 aletas por polegada', '5', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (111, 28, 'C', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1433, 335, '6mm', 'G', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1434, 336, 'A ar', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1435, 336, 'Elétrico no núcleo e bandeja', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1436, 336, 'Ar no núcleo e elétrico na bandeja', 'F', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1437, 336, 'A gás no núcleo e bandeja', 'G', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1438, 336, 'A gás no núcleo e elétrico na bandeja', 'H', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1439, 336, 'A gás quente no núcleo', 'I', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1440, 337, 'Cobre', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1441, 338, 'Expansão direta conexão rosca (SAE)', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1442, 339, 'Sem acessórios', '00', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1443, 339, 'Válvula de Expansão', '01', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1444, 339, 'Válvula Solenóide', '02', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1445, 339, 'Resistência de dreno', '03', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1446, 339, 'Bandeja dupla isolada', '04', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1447, 340, 'Gabinete em alumínio liso', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1448, 340, 'Gabinete em alumínio liso e proteção N1 nas aletas', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1449, 340, 'Gabinete em alumínio liso e proteção N2 nas aletas', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1450, 340, 'Gabinete em alumínio com pintura epóxi branca', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1451, 340, 'Gabinete em alumínio com pintura epóxi branca e proteção N1', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1452, 340, 'Gabinete em alumínio com pintura epóxi branca e proteção N2', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1453, 341, 'AC', 'MAC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1454, 341, 'Eletrônico EC', 'MEC', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1455, 341, 'Eletrônico de uma velocidade (ECM ou IQ)', 'M1V', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1456, 341, 'Eletrônico de duas velocidades (ECQ ou ESM)', 'M2V', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1457, 342, '220V/1F/60Hz', 'N', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1458, 343, 'Engradado', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1459, 343, 'Caixa de madeira', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1460, 343, 'EPE + Filme PVC', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1544, 377, '4,5mm (modelo A)', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1545, 377, '8,0mm (modelo B)', 'H', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1546, 378, 'A ar', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1547, 378, 'Elétrico no núcleo e bandeja', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1548, 378, 'Ar no núcleo e elétrico na bandeja', 'F', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1549, 378, 'A gás no núcleo e bandeja', 'G', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1550, 378, 'A gás no núcleo e elétrico na bandeja', 'H', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1551, 378, 'A água', 'J', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1552, 378, 'A água e elétrico na bandeja', 'K', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1553, 378, 'A água, gás quente no núcleo e na bandeja', 'L', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1554, 378, 'A água, gás quente no núcleo e elétrico na bandeja', 'M', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1555, 378, 'A água e elétrico no núcleo e bandeja', 'N', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1556, 379, 'Alumínio', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1557, 379, 'Cobre para Co2', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1558, 379, 'Cobre', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1559, 380, 'Expansão Direta', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1560, 380, '2 Coletores', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1561, 380, '2 Coletores com Flanges', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1562, 380, '2 Coletores com Niples', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1563, 380, '2 Coletores Roscados (Al)', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1564, 380, 'Expansão Direta e Bandeja Dupla Isolada', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1565, 380, '2 Coletores e Bandeja Dupla Isolada', 'G', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1566, 380, '2 Coletores com Flanges e Bandeja Dupla Isolada', 'H', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1567, 380, '2 Coletores com Niples e Bandeja Dupla Isolada', 'I', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1568, 380, '2 Coletores Roscados (Al) e Bandeja Dupla Isolada', 'J', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1569, 381, 'Sem acessórios', '00', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1570, 381, 'Válvula de Expansão', '01', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1571, 381, 'Válvula Solenóide', '02', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1572, 381, 'Resistência de dreno', '03', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1573, 381, '1 + 2', '11', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1574, 381, '2 + 3', '12', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1575, 381, '1 + 2 + 3', '13', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1576, 382, 'Gabinete de alumínio liso', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1577, 382, 'Gabinete de alumínio liso e proteção N1 nas aletas', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1578, 382, 'Gabinete de alumínio liso e proteção N2 nas aletas', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1579, 382, 'Gabinete de alumínio com pintura epóxi branca', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1580, 382, 'Gabinete de alumínio com pintura epóxi branca e proteção N1', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1581, 382, 'Gabinete de alumínio com pintura epóxi branca e proteção N2', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1582, 382, 'Gabinete de inox', 'G', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1583, 382, 'Gabinete de inox e proteção N1 nas aletas', 'H', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1584, 382, 'Gabinete de inox e proteção N2 nas aletas', 'I', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1585, 383, 'Motoventilador AC', 'MAC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1586, 383, 'Motoventilador EC', 'MEC', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1587, 384, '230V/1F/50Hz', 'G', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1588, 384, '230V/3F/50Hz', 'H', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1589, 384, '380V/3F/50Hz', 'E', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1590, 384, '230V/1F/60Hz', 'N', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1591, 384, '230V/3F/60Hz', 'Q', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1592, 384, '380V/3F/60Hz', 'V', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1593, 385, 'Caixa', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1594, 385, 'Engradado', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1938, 468, 'Natural', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1939, 468, 'Elétrico', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1940, 470, '220V-1F 60Hz', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1941, 471, '4.3', '5', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1942, 472, '1', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1943, 472, '2', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1944, 472, '3', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1945, 472, '4', '4', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1946, 472, '5', '5', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1947, 472, '6', '6', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1948, 472, '7', '7', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1949, 472, '8', '8', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (1950, 473, 'C', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2221, 545, 'EVI', 'EVI', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2222, 546, '5,0mm (modelo A)', 'D', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2223, 546, '10,0mm (modelo B)', 'I', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2224, 549, 'Natural', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2225, 549, 'Elétrico', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2226, 549, 'Ar no núcleo e elétrico na bandeja', 'F', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2227, 549, 'A gás no núcleo e bandeja', 'G', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2228, 549, 'A gás no núcleo e elétrico na bandeja', 'H', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2229, 549, 'A água', 'J', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2230, 549, 'A água, elétrico no núcleo e bandeja', 'K', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2231, 549, 'A água, gás quente no núcleo e na bandeja', 'L', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2232, 549, 'A água, gás quente no núcleo e elétrico no núcleo e na bandeja', 'M', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2233, 549, 'A água e elétrico no núcleo e na bandeja', 'N', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2234, 550, 'Alumínio', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2235, 550, 'Cobre para Co2', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2236, 550, 'Cobre', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2237, 551, 'Expansão Direta', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2238, 551, '2 Coletores', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2239, 551, '2 Coletores com Flanges', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2240, 551, '2 Coletores com Niples', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2241, 551, 'Expansão Direta e Bandeja Dupla Isolada', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2242, 551, '2 Coletores e Bandeja Dupla Isolada', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2243, 551, '2 Coletores com Flanges e Bandeja Dupla Isolada', 'G', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2244, 551, '2 Coletores com Niples e Bandeja Dupla Isolada', 'H', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2245, 551, '2 Coletores Roscados (Al) e Bandeja Dupla Isolada', 'I', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2246, 552, 'Sem acessórios', '00', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2247, 552, 'Válvula de Expansão', '01', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2248, 552, 'Válvula Solenóide', '02', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2249, 552, 'Resistência de dreno', '03', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2250, 552, '1 + 2 + 3', '10', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2251, 552, '1 + 2', '11', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2252, 552, '2 + 3', '12', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2253, 552, '1 + 3', '13', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2254, 553, 'Gabinete de aço protegido', 'G', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2255, 553, 'Gabinete de aço protegido e proteção N1 nas aletas', 'H', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2256, 553, 'Gabinete de aço protegido e proteção N2 nas aletas', 'I', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2257, 553, 'Gabinete de inox', 'M', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2258, 553, 'Gabinete de inox e proteção N1 nas aletas', 'N', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2259, 553, 'Gabinete de inox e proteção N2 nas aletas', 'O', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2260, 554, 'Motoventilador AC', 'MAC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2261, 554, 'Motoventilador EC', 'MEC', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2262, 555, '230V/3F/60Hz', 'Q', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2263, 555, '380V/3F/60Hz', 'V', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2264, 556, 'Caixa', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2265, 556, 'Engradado', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2266, 557, 'HDH', 'HDH', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2267, 558, '4,5mm (modelo A)', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2268, 558, '8,0mm (modelo B)', 'H', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2269, 559, 'Natural', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2270, 559, 'Elétrico', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2271, 559, 'Ar no núcleo e elétrico na bandeja', 'F', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2272, 559, 'A gás no núcleo e bandeja', 'G', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2273, 559, 'A gás no núcleo e elétrico na bandeja', 'H', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2274, 559, 'A água', 'J', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2275, 559, 'A água, gás quente no núcleo e na bandeja', 'K', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2276, 559, 'A água, gás quente no núcleo e elétrico no núcleo e na bandeja', 'L', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2277, 559, 'A água e elétrico no núcleo e na bandeja', 'M', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2278, 559, 'A água e elétrico no núcleo e na bandeja (2)', 'N', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2279, 562, 'Alumínio', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2280, 562, 'Cobre para Co2', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2281, 562, 'Cobre', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2282, 563, 'Expansão Direta', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2283, 563, '2 Coletores', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2284, 563, '2 Coletores com Flanges', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2285, 563, '2 Coletores com Niples', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2286, 563, 'Expansão Direta e Bandeja Dupla Isolada', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2287, 563, '2 Coletores e Bandeja Dupla Isolada', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2288, 563, '2 Coletores com Flanges e Bandeja Dupla Isolada', 'G', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2289, 563, '2 Coletores com Niples e Bandeja Dupla Isolada', 'H', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2290, 563, '2 Coletores Roscados (Al) e Bandeja Dupla Isolada', 'J', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2291, 564, 'Sem acessórios', '00', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2292, 564, 'Válvula de Expansão', '01', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2293, 564, 'Válvula Solenóide', '02', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2294, 564, 'Resistência de dreno', '03', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2295, 564, '1 + 2 + 3', '10', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2296, 564, '1 + 2', '11', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2297, 564, '2 + 3', '12', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2298, 564, '1 + 3', '13', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2299, 565, 'Gabinete de Alumínio', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2300, 565, 'Gabinete de alumínio e proteção N1 nas aletas', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2301, 565, 'Gabinete de alumínio e proteção N2 nas aletas', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2302, 565, 'Gabinete protegido', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2303, 565, 'Gabinete de al. protegido e proteção N1 nas aletas', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2304, 565, 'Gabinete de al. protegido e proteção N2 nas aletas', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2305, 565, 'Gabinete de inox', 'G', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2306, 565, 'Gabinete de inox e proteção N1 nas aletas', 'H', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2307, 565, 'Gabinete de inox e proteção N2 nas aletas', 'I', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2308, 566, 'Motoventilador AC', 'MAC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2309, 566, 'Motoventilador EC', 'MEC', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2310, 567, '220V/1F/60Hz', 'N', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2311, 567, '220V/3F/60Hz', 'Q', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2312, 567, '380V/3F 60Hz', 'V', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2313, 568, 'Caixa', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2314, 568, 'Engradado', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2315, 570, 'Cond. plano', 'ACC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2316, 570, 'Cond. V', 'ACV', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2317, 572, '6', '06', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2318, 572, '8', '08', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2319, 572, '12', '12', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2320, 573, '220V/3F/60Hz', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2321, 573, '440V/3F/60Hz', 'D', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2322, 573, '380V/3F/60Hz', 'E', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2323, 574, '1', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2324, 574, '2', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2325, 574, '3', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2326, 574, '4', '4', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2327, 574, '5', '5', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2328, 574, '6', '6', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2329, 575, 'EC', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2330, 575, 'AC', 'F', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2331, 576, '10', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2332, 576, '12', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2333, 577, 'Serpentina protegida (KKG) e gabinete sem pintura', '2', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2334, 578, 'Elgin', '0', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2335, 579, 'AC', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2336, 579, 'EC', 'C', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2654, 739, 'EVI', 'EVI', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2655, 740, '5,0mm (modelo A)', 'D', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2656, 740, '10,0mm (modelo B)', 'I', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2657, 741, 'Natural', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2658, 741, 'Elétrico', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2659, 741, 'Ar no núcleo e elétrico na bandeja', 'F', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2660, 741, 'A gás no núcleo e bandeja', 'G', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2661, 741, 'A gás no núcleo e elétrico na bandeja', 'H', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2662, 741, 'A água', 'J', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2663, 741, 'A água, elétrico no núcleo e bandeja', 'K', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2664, 741, 'A água, gás quente no núcleo e na bandeja', 'L', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2665, 741, 'A água, gás quente no núcleo e elétrico no núcleo e na bandeja', 'M', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2666, 741, 'A água e elétrico no núcleo e na bandeja', 'N', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2667, 744, 'Alumínio', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2668, 744, 'Cobre para Co2', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2669, 744, 'Cobre', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2670, 745, 'Expansão Direta', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2671, 745, '2 Coletores', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2672, 745, '2 Coletores com Flanges', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2673, 745, '2 Coletores com Niples', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2674, 745, 'Expansão Direta e Bandeja Dupla Isolada', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2675, 745, '2 Coletores e Bandeja Dupla Isolada', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2676, 745, '2 Coletores com Flanges e Bandeja Dupla Isolada', 'G', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2677, 745, '2 Coletores com Niples e Bandeja Dupla Isolada', 'H', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2678, 745, '2 Coletores Roscados (Al) e Bandeja Dupla Isolada', 'I', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2679, 746, 'Sem acessórios', '00', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2680, 746, 'Válvula de Expansão', '01', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2681, 746, 'Válvula Solenóide', '02', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2682, 746, 'Resistência de dreno', '03', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2683, 746, '1 + 2 + 3', '10', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2684, 746, '1 + 2', '11', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2685, 746, '2 + 3', '12', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2686, 746, '1 + 3', '13', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2687, 747, 'Gabinete de aço protegido', 'G', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2688, 747, 'Gabinete de aço protegido e proteção N1 nas aletas', 'H', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2689, 747, 'Gabinete de aço protegido e proteção N2 nas aletas', 'I', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2690, 747, 'Gabinete de inox', 'M', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2691, 747, 'Gabinete de inox e proteção N1 nas aletas', 'N', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2692, 747, 'Gabinete de inox e proteção N2 nas aletas', 'O', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2693, 748, 'Motoventilador AC', 'MAC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2694, 748, 'Motoventilador EC', 'MEC', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2695, 749, '230V/3F/60Hz', 'Q', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2696, 749, '380V/3F/60Hz', 'V', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2697, 750, 'Caixa', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2698, 750, 'Engradado', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2699, 751, 'HDH', 'HDH', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2700, 752, '4,5mm (modelo A)', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2701, 752, '8,0mm (modelo B)', 'H', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2702, 753, 'Natural', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2703, 753, 'Elétrico', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2704, 753, 'Ar no núcleo e elétrico na bandeja', 'F', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2705, 753, 'A gás no núcleo e bandeja', 'G', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2706, 753, 'A gás no núcleo e elétrico na bandeja', 'H', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2707, 753, 'A água', 'J', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2708, 753, 'A água, gás quente no núcleo e na bandeja', 'K', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2709, 753, 'A água, gás quente no núcleo e elétrico no núcleo e na bandeja', 'L', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2710, 753, 'A água e elétrico no núcleo e na bandeja', 'M', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2711, 753, 'A água e elétrico no núcleo e na bandeja (2)', 'N', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2712, 756, 'Alumínio', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2713, 756, 'Cobre para Co2', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2714, 756, 'Cobre', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2715, 757, 'Expansão Direta', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2716, 757, '2 Coletores', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2717, 757, '2 Coletores com Flanges', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2718, 757, '2 Coletores com Niples', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2719, 757, 'Expansão Direta e Bandeja Dupla Isolada', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2720, 757, '2 Coletores e Bandeja Dupla Isolada', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2721, 757, '2 Coletores com Flanges e Bandeja Dupla Isolada', 'G', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2722, 757, '2 Coletores com Niples e Bandeja Dupla Isolada', 'H', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2723, 757, '2 Coletores Roscados (Al) e Bandeja Dupla Isolada', 'J', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2724, 758, 'Sem acessórios', '00', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2725, 758, 'Válvula de Expansão', '01', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2726, 758, 'Válvula Solenóide', '02', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2727, 758, 'Resistência de dreno', '03', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2728, 758, '1 + 2 + 3', '10', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2729, 758, '1 + 2', '11', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2730, 758, '2 + 3', '12', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2731, 758, '1 + 3', '13', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2732, 759, 'Gabinete de Alumínio', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2733, 759, 'Gabinete de alumínio e proteção N1 nas aletas', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2734, 759, 'Gabinete de alumínio e proteção N2 nas aletas', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2735, 759, 'Gabinete protegido', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2736, 759, 'Gabinete de al. protegido e proteção N1 nas aletas', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2737, 759, 'Gabinete de al. protegido e proteção N2 nas aletas', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2738, 759, 'Gabinete de inox', 'G', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2739, 759, 'Gabinete de inox e proteção N1 nas aletas', 'H', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2740, 759, 'Gabinete de inox e proteção N2 nas aletas', 'I', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2741, 760, 'Motoventilador AC', 'MAC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2742, 760, 'Motoventilador EC', 'MEC', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2743, 761, '230V/1F/60Hz', 'N', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2744, 761, '230V/3F/60Hz', 'Q', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2745, 761, '380V/3F/60Hz', 'V', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2746, 762, 'Caixa', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2747, 762, 'Engradado', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2775, 777, 'Unidade Condensadora', 'U', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2776, 778, 'Fluxo Horizontal', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2777, 778, 'Fluxo Vertical', 'V', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2778, 779, 'Semi-Hermético', 'H', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2779, 780, 'Média/Baixa', 'MB', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2780, 780, 'Baixa/Média', 'BO', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2781, 781, 'R-404A', '4', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2782, 781, 'R-507', '4', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2783, 781, 'R-134a', '4', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2784, 783, '380V-3F 60Hz', 'J', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2785, 783, '220V-3F 60Hz', 'T', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2786, 783, '440V-3F 60Hz (1)', 'D', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2787, 783, '380V-3F 50Hz', 'F', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2788, 784, 'Condensadora Ar, Tanque de Líquido, Visor e Filtro', 'T', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2789, 784, 'Condensadora Ar Remoto, Tanque de Líquido, Visor e Filtro', 'S', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2790, 784, 'Acumulador, Filtro Sucção, Separador de Óleo e Degelo Gás Quente — Consultar Tabela de Acessórios', 'G', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2791, 785, 'Bitzer', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2792, 785, 'Dorin', 'D', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2793, 785, 'Copeland (2)', 'O', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2794, 786, '1', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2795, 787, 'C', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2796, 788, 'Acumulador, Filtro de Sucção e Separador de Óleo', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2797, 788, 'Acumulador, Filtro Sucção, Separador de Óleo e Degelo Gás Quente — Consultar Tabela de Acessórios', 'G', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2798, 789, 'Controle do Compressor (On/Off)', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2799, 789, 'Controle de Capacidade 35 a 100%', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2800, 789, 'Inversor de Frequência', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2829, 805, 'Evaporador FXB+ baixo perfil', 'FXB+', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2830, 806, '4,5 al/pol Degelo elétrico', 'E', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2831, 806, '4,5 al/pol Degelo a ar', 'N', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2832, 808, '1', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2833, 808, '2', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2834, 808, '3', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2835, 808, '4', '4', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2836, 808, '5', '5', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2837, 808, '6', '6', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2838, 809, '220V-1F 50-60Hz', 'E', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2839, 810, 'Polo Sombreado', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2840, 811, '254.0', '25', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2841, 812, 'C', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2842, 814, 'FL+E Degelo Elétrico', 'FL+E', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2843, 816, '220V-1F 50-60Hz', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2844, 817, '4', '5', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2845, 818, '1', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2846, 818, '2', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2847, 818, '3', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2848, 818, '4', '4', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2849, 818, '5', '5', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2850, 818, '6', '6', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2851, 818, '7', '7', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2852, 818, '8', '8', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2853, 819, 'Versão', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2854, 821, 'Cond. plano', 'ACC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2855, 821, 'Cond. V', 'ACV', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2856, 823, '6', '06', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2857, 823, '8', '08', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2858, 823, '12', '12', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2859, 824, '220V-3F-50/60Hz', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2860, 824, '440V-3F-60Hz', 'D', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2861, 824, '380V-3F-50/60Hz', 'E', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2862, 825, '1', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2863, 825, '2', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2864, 825, '3', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2865, 825, '4', '4', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2866, 825, '5', '5', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2867, 825, '6', '6', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2868, 826, 'EC', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2869, 826, 'AC', 'F', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2870, 827, '10', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2871, 827, '12', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2872, 828, 'ACC 100% ACV 50%/50%', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2873, 829, 'Serpentina protegida (KKG) e gabinete sem pintura', '2', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2874, 830, 'Elgin', '0', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2875, 831, 'AC', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2876, 831, 'EC', 'C', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2877, 833, 'Evaporador dupla saída de ar', 'ED', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2878, 834, 'Halogenado', 'H', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2879, 835, '300.0', '3O', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2880, 836, '1', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2881, 836, '2', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2882, 836, '3', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2883, 836, '4', '4', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2884, 836, '5', '5', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2885, 837, '2', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2886, 837, '3', 'C', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2887, 837, '4', 'D', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2888, 838, '6 al/pol Degelo a ar', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2889, 838, '4 al/pol Degelo elétrico', 'L', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2890, 838, '6 al/pol Degelo elétrico', 'E', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2891, 839, '220V-1F 50-60Hz', 'J', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2892, 840, 'Gabinete alumínio aleta alumínio', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2893, 840, 'Gabinete pintado aleta protegida', 'P', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2894, 841, 'Convencional', 'J', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2895, 841, 'Eletrônico 1 velocidade', 'K', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2896, 842, 'Ventur', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2897, 843, 'Sem válvula', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2898, 843, 'R-134a', '1', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2899, 843, 'R-404A', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2900, 844, 'Sem orifício', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2901, 844, 'Orifício O1', '1', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2902, 844, 'Orifício O2', '2', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2903, 844, 'Orifício O3', '3', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2904, 844, 'Orifício O4', '4', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2905, 844, 'Orifício O5', '5', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2906, 844, 'Orifício O6', '6', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2907, 845, 'Sem/Sin', 'O', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2908, 846, 'B', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2909, 849, 'Evaporador dupla saída de ar', 'ED', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2910, 850, 'Halogenado', 'H', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2911, 851, '300.0', '3O', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2912, 852, '1', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2913, 852, '2', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2914, 852, '3', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2915, 852, '4', '4', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2916, 852, '5', '5', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2917, 853, '2', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2918, 853, '3', 'C', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2919, 853, '4', 'D', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2920, 854, '6 al/pol Degelo a ar', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2921, 854, '4 al/pol Degelo elétrico', 'L', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2922, 854, '6 al/pol Degelo elétrico', 'E', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2923, 855, '220V-1F 50-60Hz', 'J', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2924, 856, 'Gabinete alumínio aleta alumínio', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2925, 856, 'Gabinete pintado aleta protegida', 'P', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2926, 857, 'Convencional', 'J', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2927, 857, 'Eletrônico 1 velocidade', 'K', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2928, 858, 'Ventur', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2929, 859, 'Sem válvula', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2930, 859, 'R-134a', '1', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2931, 859, 'R-404A', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2932, 860, 'Sem orifício', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2933, 860, 'Orifício O1', '1', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2934, 860, 'Orifício O2', '2', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2935, 860, 'Orifício O3', '3', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2936, 860, 'Orifício O4', '4', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2937, 860, 'Orifício O5', '5', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2938, 860, 'Orifício O6', '6', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2939, 861, 'Sem/Sin', 'O', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2940, 862, 'B', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2941, 865, 'Evaporador de Ar Forçado Baixo Perfil', 'GS2', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2942, 866, '6mm', 'G', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2943, 867, 'Natural', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2944, 867, 'Elétrico', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2945, 867, 'Ar no núcleo e elétrico na bandeja', 'F', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2946, 867, 'A gás no núcleo e bandeja', 'G', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2947, 867, 'A gás no núcleo e elétrico na bandeja', 'H', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2948, 867, 'A gás quente no núcleo', 'I', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2949, 869, 'Cobre', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2950, 870, 'Expansão direta conexão rosca (SAE)', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2951, 871, 'Sem acessórios', '00', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2952, 871, 'Válvula de Expansão', '01', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2953, 871, 'Válvula Solenóide', '02', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2954, 871, 'Resistência de dreno', '03', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2955, 871, 'Bandeja dupla isolada', '04', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2956, 871, '01 + 02 + 03', '10', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2957, 871, '01 + 02', '11', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2958, 871, '02 + 03', '12', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2959, 871, '01 + 03', '13', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2960, 871, '01 + 04', '14', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2961, 871, '02 + 04', '15', 10);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2962, 871, '03 + 04', '16', 11);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2963, 871, '01 + 02 + 03 + 04', '17', 12);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2964, 871, '01 + 02 + 04', '18', 13);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2965, 871, '02 + 03 + 04', '19', 14);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2966, 871, '01 + 03 + 04', '20', 15);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2967, 872, 'Gabinete em alumínio liso', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2968, 872, 'Gabinete em alumínio liso e proteção N1 nas aletas', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2969, 872, 'Gabinete em alumínio liso e proteção N2 nas aletas', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2970, 872, 'Gabinete em alumínio com pintura epóxi branca', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2971, 872, 'Gabinete em alumínio com pintura epóxi branca e proteção N1 nas aletas', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2972, 872, 'Gabinete em alumínio com pintura epóxi branca e proteção N2 nas aletas', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2973, 873, 'AC', 'MAC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2974, 873, 'Eletrônico EC', 'MEC', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2975, 873, 'Eletrônico de uma velocidade (ECM ou IQ)', 'M1V', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2976, 873, 'Eletrônico de duas velocidades (ECQ ou ESM)', 'M2V', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2977, 874, '230V/1F/50Hz', 'G', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2978, 874, '230V/1F/60Hz', 'N', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2979, 875, 'Engradado', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2980, 875, 'Caixa de madeira', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2981, 875, 'EPE + Filme PVC', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2982, 877, 'Unidade Condensadora', 'U', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2983, 878, 'Fluxo horizontal', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2984, 879, 'Scroll', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2985, 879, 'Semi Hermético Alternativo/Recíproco', 'H', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2986, 880, 'Média/Baixo', 'MB', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2987, 880, 'Baixa/Bajo', 'BO', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2988, 881, 'R-404A', '4', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2989, 881, 'R-507', '4', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2990, 881, 'R-134a', '4', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2991, 881, 'R-448A', '4', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2992, 881, 'R-449A', '4', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2993, 883, '380V-3F 60Hz', 'J', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2994, 883, '220V-3F 60Hz', 'T', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2995, 883, '440V-3F 60Hz', 'D', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2996, 883, '380V-3F 50Hz', 'F', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2997, 884, 'Tanque de Líquido, Visor e Filtro', 'T', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2998, 885, 'Elgin', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (2999, 885, 'Copeland', '0', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3000, 885, 'Bitzer (Semi Hermético Alt./Recíproco)', 'B', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3001, 885, 'Dorin (Semi Hermético Alt./Recíproco)', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3002, 886, 'Sem Gabinete', 'N', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3003, 886, 'Com Gabinete', 'T', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3004, 887, 'C', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3005, 888, 'Básica', '0', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3006, 888, 'Completa', 'C', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3007, 888, 'Completa com degelo a gás quente', 'G', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3008, 889, 'Básica', '0', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3009, 889, 'Completa', '1', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3010, 889, 'Completa com controle de capacidade', '2', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3011, 892, 'Unidade Condensadora', 'U', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3012, 893, 'Fluxo Horizontal', 'S', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3013, 893, 'Fluxo Vertical', 'V', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3014, 894, 'Scroll', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3015, 894, 'Semi-Hermético', 'H', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3016, 895, 'Média/Baixa', 'MB', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3017, 895, 'Baixa/Média', 'BO', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3018, 896, 'R-404A', '4', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3019, 896, 'R-507', '4', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3020, 896, 'R-134a', '4', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3021, 898, '380V-3F 60Hz', 'J', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3022, 898, '220V-3F 60Hz', 'T', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3023, 898, '440V-3F 60Hz (1)', 'D', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3024, 899, 'Condensadora Ar, Tanque de Líquido, Visor e Filtro Ar, Tanque de Líquido, Visor e Filtro', 'T', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3025, 899, 'Condensadora Ar Remoto, Tanque de Líquido, Visor e FiltroAr Remoto, Tanque de Líquido, Visor e Filtro', 'S', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3026, 900, 'Bitzer', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3027, 900, 'Dorin', 'D', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3028, 900, 'Copeland (2)', 'O', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3029, 901, '2', '2', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3030, 901, '3', '3', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3031, 902, 'C', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3032, 903, 'Acumulador, Filtro de Sucção e Separador de Óleo, Filtro de Sucção e Separador de Óleo', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3033, 903, 'Acumulador, Filtro Sucção, Separador de Óleo e Degelo Gás Quente', 'G', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3034, 904, 'Controle do Compressor (On/Off)', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3035, 904, 'Controle de Capacidade 35 to 100%', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3036, 906, 'Natural', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3037, 906, 'Elétrico', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3038, 907, 'Degelo a ar', 'FMA', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3039, 907, 'Degelo Elétrico', 'FME', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3040, 909, '220V/3F/60Hz', 'C', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3041, 909, '440V/3F/60Hz (1)', 'D', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3042, 909, '380V/3F/60Hz', 'E', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3043, 909, '220V/1F/60Hz', 'B', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3044, 910, '4 al/pol', '4', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3045, 910, '6 al/pol', '6', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3046, 911, '1', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3047, 911, '2', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3048, 911, '3', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3049, 911, '4', '4', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3050, 911, '5', '5', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3051, 912, 'Versão', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3052, 914, 'Degelo a ar', 'FMA', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3053, 914, 'Degelo Elétrico', 'FME', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3054, 915, 'Natural', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3055, 915, 'Elétrico', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3056, 917, '220V/1F/60Hz', 'B', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3057, 917, '220V/3F/60Hz', 'C', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3058, 917, '440V/3F/60Hz (1)', 'D', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3059, 917, '380V/3F/60Hz', 'E', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3060, 918, '4 al/pol', '4', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3061, 918, '6 al/pol', '6', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3062, 919, '1', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3063, 919, '2', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3064, 919, '3', '3', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3065, 919, '4', '4', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3066, 919, '5', '5', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3067, 920, 'Versão', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3158, 941, 'Evaporador de Ar Forçado Alto Perfil', 'EVI', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3159, 942, '5,0mm (modelo A)', 'D', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3160, 942, '10,0mm (modelo B)', 'I', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3161, 943, 'A ar', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3162, 943, 'Elétrico no núcleo e bandeja', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3163, 943, 'Ar no núcleo e elétrico na bandeja', 'F', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3164, 943, 'A gás no núcleo e bandeja', 'G', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3165, 943, 'A gás no núcleo e elétrico na bandeja', 'H', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3166, 943, 'A água', 'J', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3167, 943, 'A água e elétrico na bandeja', 'K', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3168, 943, 'A água, gás quente no núcleo e na bandeja', 'L', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3169, 943, 'A água, gás quente no núcleo e elétrico na bandeja', 'M', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3170, 943, 'A água e elétrico no núcleo e bandeja', 'N', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3171, 945, 'Alumínio', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3172, 945, 'Cobre para Co2', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3173, 945, 'Cobre', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3174, 946, 'Expansão Direta', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3175, 946, '2 Coletores', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3176, 946, '2 Coletores com Flanges', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3177, 946, '2 Coletores com Niples', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3178, 946, '2 Coletores Roscados (Al)', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3179, 946, 'Expansão Direta e Bandeja Dupla Isolada', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3180, 946, '2 Coletores e Bandeja Dupla Isolada', 'G', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3181, 946, '2 Coletores com Flanges e Bandeja Dupla Isolada', 'H', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3182, 946, '2 Coletores com Niples e Bandeja Dupla Isolada', 'I', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3183, 946, '2 Coletores Roscados (Al) e Bandeja Dupla Isolada', 'J', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3184, 947, 'Sem acessórios', '00', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3185, 947, 'Válvula de Expansão', '01', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3186, 947, 'Válvula Solenóide', '02', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3187, 947, 'Resistência de dreno', '03', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3188, 947, '1 + 2', '11', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3189, 947, '2 + 3', '12', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3190, 947, '1 + 2 + 3', '13', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3191, 948, 'Gabinete de aço protegido', 'G', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3192, 948, 'Gabinete de aço protegido e proteção N1 nas aletas', 'H', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3193, 948, 'Gabinete de aço protegido e proteção N2 nas aletas', 'I', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3194, 948, 'Gabinete de inox', 'M', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3195, 948, 'Gabinete de inox e proteção N1 nas aletas', 'N', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3196, 948, 'Gabinete de inox e proteção N2 nas aletas', 'O', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3197, 949, 'Motoventilador AC', 'MAC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3198, 949, 'Motoventilador EC', 'MEC', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3199, 950, '230V/3F/60Hz', 'Q', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3200, 950, '380V/3F/60Hz', 'V', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3201, 951, 'Caixa', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3202, 951, 'Engradado', '2', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3203, 952, 'Evaporador de Ar Forçado Alto Perfil', 'EVI', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3204, 953, '5,0mm (modelo A)', 'D', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3205, 953, '10,0mm (modelo B)', 'I', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3206, 954, 'A ar', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3207, 954, 'Elétrico no núcleo e bandeja', 'E', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3208, 954, 'Ar no núcleo e elétrico na bandeja', 'F', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3209, 954, 'A gás no núcleo e bandeja', 'G', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3210, 954, 'A gás no núcleo e elétrico na bandeja', 'H', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3211, 954, 'A água', 'J', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3212, 954, 'A água e elétrico na bandeja', 'K', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3213, 954, 'A água, gás quente no núcleo e na bandeja', 'L', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3214, 954, 'A água, gás quente no núcleo e elétrico na bandeja', 'M', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3215, 954, 'A água e elétrico no núcleo e bandeja', 'N', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3216, 956, 'Alumínio', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3217, 956, 'Cobre para Co2', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3218, 956, 'Cobre', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3219, 957, 'Expansão Direta', 'A', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3220, 957, '2 Coletores', 'B', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3221, 957, '2 Coletores com Flanges', 'C', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3222, 957, '2 Coletores com Niples', 'D', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3223, 957, '2 Coletores Roscados (Al)', 'E', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3224, 957, 'Expansão Direta e Bandeja Dupla Isolada', 'F', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3225, 957, '2 Coletores e Bandeja Dupla Isolada', 'G', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3226, 957, '2 Coletores com Flanges e Bandeja Dupla Isolada', 'H', 7);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3227, 957, '2 Coletores com Niples e Bandeja Dupla Isolada', 'I', 8);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3228, 957, '2 Coletores Roscados (Al) e Bandeja Dupla Isolada', 'J', 9);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3229, 958, 'Sem acessórios', '00', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3230, 958, 'Válvula de Expansão', '01', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3231, 958, 'Válvula Solenóide', '02', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3232, 958, 'Resistência de dreno', '03', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3233, 958, '1 + 2', '11', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3234, 958, '2 + 3', '12', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3235, 958, '1 + 2 + 3', '13', 6);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3236, 959, 'Gabinete de aço protegido', 'G', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3237, 959, 'Gabinete de aço protegido e proteção N1 nas aletas', 'H', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3238, 959, 'Gabinete de aço protegido e proteção N2 nas aletas', 'I', 2);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3239, 959, 'Gabinete de inox', 'M', 3);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3240, 959, 'Gabinete de inox e proteção N1 nas aletas', 'N', 4);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3241, 959, 'Gabinete de inox e proteção N2 nas aletas', 'O', 5);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3242, 960, 'Motoventilador AC', 'MAC', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3243, 960, 'Motoventilador EC', 'MEC', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3244, 961, '230V/3F/60Hz', 'Q', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3245, 961, '380V/3F/60Hz', 'V', 1);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3246, 962, 'Caixa', '1', 0);
INSERT INTO "campo_catalogo_opcao" ("id", "campo_id", "valor", "codigo", "ordem") VALUES (3247, 962, 'Engradado', '2', 1);