-- tabela_compatibilidade_valvula — bloco 1 de 1 (296 registros no total)

INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (1, 'E2V 01', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (2, 'E2V 01', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (3, 'E2V 01', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (4, 'E2V 01', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (5, 'E2V 01', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (6, 'E2V 03', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (7, 'E2V 03', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (8, 'E2V 03', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (9, 'E2V 03', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (10, 'E2V 03', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (11, 'E2V 05', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (12, 'E2V 05', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (13, 'E2V 05', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (14, 'E2V 05', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (15, 'E2V 05', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (16, 'E2V 09', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (17, 'E2V 09', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (18, 'E2V 09', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (19, 'E2V 09', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (20, 'E2V 09', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (21, 'E2V 11', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (22, 'E2V 11', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (23, 'E2V 11', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (24, 'E2V 11', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (25, 'E2V 11', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (26, 'E2V 14', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (27, 'E2V 14', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (28, 'E2V 14', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (29, 'E2V 14', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (30, 'E2V 14', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (31, 'E2V 18', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (32, 'E2V 18', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (33, 'E2V 18', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (34, 'E2V 18', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (35, 'E2V 18', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (36, 'E2V 24', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (37, 'E2V 24', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (38, 'E2V 24', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (39, 'E2V 24', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (40, 'E2V 24', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (41, 'E2V 30', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (42, 'E2V 30', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (43, 'E2V 30', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (44, 'E2V 30', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (45, 'E2V 30', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (46, 'E2V 35', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (47, 'E2V 35', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (48, 'E2V 35', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (49, 'E2V 35', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (50, 'E2V 35', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (51, 'E3V 30', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (52, 'E3V 30', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (53, 'E3V 30', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (54, 'E3V 30', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (55, 'E3V 30', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (56, 'E3V 35', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (57, 'E3V 35', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (58, 'E3V 35', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (59, 'E3V 35', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (60, 'E3V 35', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (61, 'E3V 45', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (62, 'E3V 45', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (63, 'E3V 45', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (64, 'E3V 45', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (65, 'E3V 45', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (66, 'E3V 55', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (67, 'E3V 55', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (68, 'E3V 55', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (69, 'E3V 55', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (70, 'E3V 55', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (71, 'E3V 65', 'Evd Mini');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (72, 'E3V 65', 'EVD Ice');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (73, 'E3V 65', 'MPX Pro');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (74, 'E3V 65', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (75, 'E3V 65', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (76, 'E4V 65', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (77, 'E4V 65', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (78, 'E4V 85', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (79, 'E4V 85', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (80, 'E4V 95', 'EVD Evolution');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (81, 'E4V 95', 'pCO');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (82, 'SB103T', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (83, 'SB103T', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (84, 'SB103T', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (85, 'SB105T', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (86, 'SB105T', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (87, 'SB105T', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (88, 'SB108', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (89, 'SB108', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (90, 'SB108', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (91, 'SB108T', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (92, 'SB108T', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (93, 'SB108T', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (94, 'SB110', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (95, 'SB110', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (96, 'SB110', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (97, 'SB110T', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (98, 'SB110T', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (99, 'SB110T', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (100, 'SB114', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (101, 'SB114', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (102, 'SB114', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (103, 'SB114T', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (104, 'SB114T', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (105, 'SB114T', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (106, 'SB118', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (107, 'SB118', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (108, 'SB118', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (109, 'SB118T', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (110, 'SB118T', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (111, 'SB118T', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (112, 'SB124', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (113, 'SB124', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (114, 'SB124', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (115, 'SB124T', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (116, 'SB124T', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (117, 'SB124T', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (118, 'SB130', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (119, 'SB130', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (120, 'SB130', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (121, 'SB130T', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (122, 'SB130T', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (123, 'SB130T', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (124, 'SB132', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (125, 'SB132', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (126, 'SB132', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (127, 'SB132T', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (128, 'SB132T', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (129, 'SB132T', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (130, 'SB145', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (131, 'SB145', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (132, 'SB145', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (133, 'SB152', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (134, 'SB152', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (135, 'SB152', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (136, 'SB155', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (137, 'SB155', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (138, 'SB155', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (139, 'SB162', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (140, 'SB162', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (141, 'SB162', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (142, 'SB2012', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (143, 'SB2012', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (144, 'SB2012', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (145, 'SB2025', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (146, 'SB2025', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (147, 'SB2025', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (148, 'SB2100', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (149, 'SB2100', 'VX-1025EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (150, 'SB2100', 'VX-1225');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (151, 'SB2050', 'VX-1050E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (152, 'SB2050', 'VX-1050EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (153, 'SB2150', 'VX-1050E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (154, 'SB2150', 'VX-1050EW');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (155, 'TEX2', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (156, 'TEX2', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (157, 'TEX2', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (158, 'TEX2', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (159, 'TEX2', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (160, 'TEX2', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (161, 'TEX2', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (162, 'TEX5', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (163, 'TEX5', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (164, 'TEX5', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (165, 'TEX5', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (166, 'TEX5', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (167, 'TEX5', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (168, 'TEX5', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (169, 'TEX12', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (170, 'TEX12', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (171, 'TEX12', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (172, 'TEX12', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (173, 'TEX12', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (174, 'TEX12', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (175, 'TEX12', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (176, 'TEX20', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (177, 'TEX20', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (178, 'TEX20', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (179, 'TEX20', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (180, 'TEX20', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (181, 'TEX20', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (182, 'TEX20', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (183, 'TEX55', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (184, 'TEX55', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (185, 'TEX55', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (186, 'TEX55', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (187, 'TEX55', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (188, 'TEX55', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (189, 'TEX55', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (190, 'TEZ2', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (191, 'TEZ2', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (192, 'TEZ2', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (193, 'TEZ2', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (194, 'TEZ2', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (195, 'TEZ2', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (196, 'TEZ2', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (197, 'TEZ5', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (198, 'TEZ5', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (199, 'TEZ5', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (200, 'TEZ5', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (201, 'TEZ5', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (202, 'TEZ5', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (203, 'TEZ5', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (204, 'TEZ12', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (205, 'TEZ12', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (206, 'TEZ12', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (207, 'TEZ12', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (208, 'TEZ12', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (209, 'TEZ12', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (210, 'TEZ12', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (211, 'TEZ20', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (212, 'TEZ20', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (213, 'TEZ20', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (214, 'TEZ20', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (215, 'TEZ20', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (216, 'TEZ20', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (217, 'TEZ20', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (218, 'TEZ55', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (219, 'TEZ55', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (220, 'TEZ55', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (221, 'TEZ55', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (222, 'TEZ55', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (223, 'TEZ55', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (224, 'TEZ55', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (225, 'TEN2', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (226, 'TEN2', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (227, 'TEN2', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (228, 'TEN2', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (229, 'TEN2', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (230, 'TEN2', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (231, 'TEN2', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (232, 'TEN5', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (233, 'TEN5', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (234, 'TEN5', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (235, 'TEN5', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (236, 'TEN5', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (237, 'TEN5', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (238, 'TEN5', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (239, 'TEN12', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (240, 'TEN12', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (241, 'TEN12', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (242, 'TEN12', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (243, 'TEN12', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (244, 'TEN12', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (245, 'TEN12', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (246, 'TEN20', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (247, 'TEN20', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (248, 'TEN20', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (249, 'TEN20', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (250, 'TEN20', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (251, 'TEN20', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (252, 'TEN20', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (253, 'TEN55', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (254, 'TEN55', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (255, 'TEN55', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (256, 'TEN55', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (257, 'TEN55', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (258, 'TEN55', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (259, 'TEN55', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (260, 'TES2', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (261, 'TES2', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (262, 'TES2', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (263, 'TES2', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (264, 'TES2', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (265, 'TES2', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (266, 'TES2', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (267, 'TES5', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (268, 'TES5', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (269, 'TES5', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (270, 'TES5', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (271, 'TES5', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (272, 'TES5', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (273, 'TES5', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (274, 'TES12', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (275, 'TES12', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (276, 'TES12', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (277, 'TES12', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (278, 'TES12', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (279, 'TES12', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (280, 'TES12', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (281, 'TES20', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (282, 'TES20', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (283, 'TES20', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (284, 'TES20', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (285, 'TES20', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (286, 'TES20', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (287, 'TES20', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (288, 'TES55', 'MT512');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (289, 'TES55', 'MT512 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (290, 'TES55', 'TC900E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (291, 'TES55', 'TC900 eLog');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (292, 'TES55', 'IR33');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (293, 'TES55', 'PJEZ');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (294, 'TES55', 'PJEZY');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (295, 'SB513', 'VX-1025E');
INSERT INTO "tabela_compatibilidade_valvula" ("id", "valvula_modelo", "controlador_modelo") VALUES (296, 'SB520', 'VX-1025E');