-- catalogo_comercial — bloco 1 de 1 (34 registros no total)

INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (1, 'Porta Frigorífica', 'Genérico - Portas', 'Porta Frigorífica Correr (PFC)', 'Porta Frigorífica Industrial Correr', 'A Porta de Correr Industrial foi desenvolvida para ambientes que demandam movimentação frequente de pessoas e equipamentos, sem necessidade de vedação total. Com espessura de 70 mm e núcleo em PIR AP, a porta pode contribuir para a leveza do conjunto e auxiliar na eficiência do uso diário. A proteção superior do trilho (carenagem) é fornecida de série, favorecendo a durabilidade e a segurança da operação.
O modelo pode ser personalizado com opcionais como fechadura, bumpers e kit visor, ampliando sua funcionalidade de acordo com as necessidades do projeto. O acabamento em perfis de aço agrega resistência à estrutura.
Aplicações
  1) Indicada para instalações industriais, depósitos e galpões, onde há circulação intensa de pessoas e equipamentos, mas sem a exigência de estanqueidade total.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/cb84474780624011a2ab67fcf91cd7b8.jpg', '5.1.3.7', '5.1.3.7-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (2, 'Porta Frigorífica', 'Genérico - Portas', 'Porta Frigorífica Embutir (PFE)', 'Porta Frigorífica Industrial Embutir', 'A Porta Giratória Bloco de Fechamento foi desenvolvida para atender às exigências específicas de túneis de congelamento (temperaturas abaixo de -30 °C) e grandes vãos-luzes. Seu sistema de vedação reforçado com blocos de fechamento proporciona excelente isolamento térmico, sendo uma solução robusta e confiável para aplicações industriais. Com estrutura em alumínio e núcleo de PIR AP, a porta combina durabilidade, resistência e eficiência térmica. Disponível em diferentes espessuras e dimensões, adapta-se a projetos personalizados e demandas de alta performance.
Este modelo utiliza um sistema de abertura por alavanca, com a opção de segurança interna para maior proteção. Portas com altura de até 2200 mm contam com dois blocos de fechamento, enquanto portas acima dessa altura possuem três blocos para vedação ainda mais eficiente.
Aplicações
  1) Ideal para túneis de congelamento, câmaras frigoríficas e ambientes industriais que requerem isolamento térmico e vedação reforçada em grandes vãos-luzes. Atende a indústrias alimentícias, centros de armazenamento e outras instalações que demandam alta eficiência em controle de temperatura.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/a2b5581d3e8d4c14800a903c50802fd9.jpg', '5.1.3.8', '5.1.3.8-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (3, 'Porta Frigorífica', 'Genérico - Portas', 'Porta Sala Limpa Isoplana Embutir (PSE)', 'Porta Isoplana - Sala Limpa', 'A Porta Giratória Sala Limpa (GSL) foi desenvolvida para ambientes que demandam controle de higiene e vedação, como hospitais, clínicas, escritórios, salas limpas, aeroportos e escolas. Conta com borracha de vedação em todo o perímetro, que pode auxiliar na redução da passagem de poeira e luminosidade.
Fabricada com maçanetas em aço inox e marco em alumínio, a porta é resistente à corrosão e está disponível em espessuras de 32 mm e 50 mm. É compatível com diferentes dimensões de vão-luz e pode receber acessórios opcionais conforme a necessidade do projeto.
Aplicações
  * Indicada para escritórios, clínicas, hospitais, aeroportos, escolas e salas limpas. Pode contribuir para ambientes que exigem requisitos de higiene, vedação e funcionalidade.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/0500ee98f7574f7dadc769593ede672b.jpg', '5.1.3.5', '5.1.3.5-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (4, 'Porta Frigorífica', 'Genérico - Portas', 'Porta Rígida Vai-Vem (PVV)', 'Porta Vai e Vem Rígida', 'A Porta Vai e Vem é projetada para ambientes com temperatura próxima à ambiente e alto fluxo de passagem. Sua estrutura robusta e núcleo de PIR AP garantem resistência a impactos causados pelo movimento de pessoas e carrinhos. O modelo conta com visor padrão em acrílico ou policarbonato, proporcionando segurança e praticidade no dia a dia. Disponível em opções de folha simples ou dupla, adapta-se às necessidades específicas de diferentes projetos.
Fabricada com marco em alumínio e espessura de 40 mm, a porta apresenta fácil instalação e é compatível com acessórios como bumpers padrão e especiais em formato de asa de avião, que prolongam a vida útil do produto.
Aplicações
  1) A Porta Vai e Vem é indicada para ambientes comerciais e industriais com alto fluxo de pessoas ou carrinhos, como supermercados, cozinhas industriais, centros de distribuição e áreas logísticas. Ideal para locais onde o impacto na folha é frequente e a estanqueidade não é uma exigência.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/789dc98df15a455a833bf592365bc923.jpg', '5.1.3.9', '5.1.3.9-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (5, 'Porta Frigorífica', 'Diversos Isopainel - Portas', 'Porta Seccional Manual (PSM)', 'Porta Seccional 90', 'A Porta Seccional 90º foi desenvolvida para aplicações industriais e comerciais em ambientes com pé-direito reduzido ou interferências acima do vão-luz. Possui núcleo em PIR AP e estrutura em painéis metálicos, que podem contribuir para o isolamento térmico e auxiliar na resistência do conjunto. Os trilhos horizontais e verticais permitem operação em locais com restrições de espaço, e o modelo é compatível com sistemas automáticos.
Todas as portas seccionais incluem travas de segurança em caso de rompimento do cabo de içamento, trancas internas para impedir a abertura externa, sistema de elevação com molas que reduz o esforço manual e borrachas em todo o perímetro, que podem auxiliar na vedação contra poeira e luminosidade. O modelo conta ainda com dois visores padrão em acrílico.
Aplicações
  1) Indicada para galpões, depósitos, fábricas e outros ambientes industriais ou comerciais, especialmente em locais com restrições de espaço. A opção de abertura semi-guilhotina pode ampliar a versatilidade de uso, adaptando-se a diferentes configurações operacionais.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/64f0eaee91b24bd186092638681dcdfe.jpg', '5.1.3.3', '5.1.3.3-2');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (6, 'Porta Frigorífica', 'Genérico - Portas', 'Portal de Selamento Maleável (PSM)', 'Portal de Selamento', 'O sistema vedante foi projetado para ser utilizado em todas as portas seccionais, proporcionando uma vedação eficiente contra perda térmica, entrada de sujeira e insetos. 
A vedação frontal é composta por lonas robustas em PVC na cor preta, com 700 mm de largura. O sistema possui um design padrão de 3400 mm de largura por 3500 mm de altura, garantindo cobertura ideal para diferentes tipos de veículos de carga. 
Para reforçar a vedação, o sistema inclui laterais de 700 mm entre as lonas frontais e a parede onde o sistema é instalado.
A estrutura é fabricada em aço galvanizado, garantindo alta resistência e durabilidade. Conta ainda com um dispositivo de recolhimento, que se ajusta a diferentes carrocerias e absorve leves impactos, garantindo um encaixe preciso e seguro. 
Esse sistema é essencial para ambientes frigoríficos e áreas que exigem controle térmico e sanitário durante operações logísticas.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/f0997d3042cb4d3cb13134e44ae71fe0.jpg', '5.1.3.6', '5.1.3.6-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (7, 'Painel Térmico tipo PIR', 'Genérico - Painel', 'Painel Isolante PIR ', 'Painel Isolante PIR', 'O Painel EasyFrigo, também conhecido como painel frigorífico, oferece uma vedação perfeita, e uma excelente resistência contra impactos. Ele possui um sistema exclusivo de encaixe macho-fêmea, oferecendo uma vedação térmica impecável, e uma alta resistência mecânica.
O núcleo, conhecido como camada intermediária, é composto por Espuma Termoisolante de Poliisocianurato (PIR), que estabiliza a temperatura interna e reduz a transferência de calor entre o exterior e o interior, contribuindo para a eficiência energética em sistemas de refrigeração e climatização.
Esses painéis são ideais para ambientes como frigoríficos e outros locais que exigem um rigoroso controle de ar, temperatura, umidade, iluminação e a presença de micróbiose partículas pequenas. Além disso, sua montagem é fácil, rápida e modular, e são fabricados em linhas contínuas automáticas, garantindo qualidade, desempenho térmico e resistência excepcional.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/b9c68261f81343358be29aba242bf416.jpg', '5.1.1.1', '5.1.1.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (8, 'Painel Térmico tipo PIR', 'Genérico - Portas', 'Porta Seccional Manual (PSM)', 'Porta Seccional Guilhotina', 'A Porta Seccional Guilhotina foi desenvolvida para locais com espaço livre na parede, dispensando o uso de trilhos horizontais. Esse formato pode favorecer operações de carga e descarga ao reduzir riscos de colisão.
Com núcleo em PIR AP, a porta pode contribuir para o isolamento térmico e ser configurada em diferentes dimensões, de acordo com as necessidades do projeto.
Aplicações
  * Indicada para galpões, depósitos, fábricas e outros ambientes industriais ou comerciais. A instalação é especialmente recomendada em locais com espaço vertical disponível e que demandam praticidade operacional.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/2c5e5d4f5e7e45d08b111bf0cdcce726.jpg', '5.1.3.3', '5.1.3.3-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (9, 'Painel Térmico tipo PIR', 'Genérico - Portas', 'Porta Rápida Enrolar (PFR)', 'Porta Rápida', 'A Porta Rápida foi desenvolvida para grandes dimensões e ambientes externos, com abertura e fechamento rápidos que podem contribuir para a produtividade. Projetada para resistir a ventos de até 100 km/h, é adequada para locais com alto fluxo de movimentação e que demandam segurança operacional.
Sua estrutura é confeccionada em aço pintado ou galvanizado a fogo e pode ser equipada com sistemas automatizados. A porta também pode receber acessórios como acionamento remoto, fotocélulas e módulos adicionais, possibilitando adaptação a diferentes contextos industriais e logísticos.
Aplicações
  1) Indicada para vãos de até 60 m² em áreas externas expostas à ação do vento, como moegas, entradas de trens e caminhões. Pode ser utilizada em operações logísticas e industriais que exigem alta frequência de abertura e fechamento, contribuindo para a eficiência e para o controle térmico.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/bfcf441b080e41c4bdfa2077a1cd3831.jpg', '5.1.3.2', '5.1.3.2-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (10, 'Painel Térmico tipo PIR', 'Genérico - Portas', 'Cortina PVC em Tiras Sobrepostas (FTS)', 'Cortina PVC', 'A Cortina de PVC é uma solução eficaz para minimizar a perda de frio em câmaras frias, evitando a entrada de contaminantes como insetos e poeira, sem comprometer a visibilidade entre os ambientes. Sua instalação é recomendada para qualquer abertura ou porta interna de uma câmara fria.
Para maior segurança operacional, a cortina conta com marcação lateral e tiras laranjas que destacam o tamanho do vão, auxiliando na orientação visual dos operadores. 
As dimensões da cortina são configuráveis de acordo com o vão-luz da abertura ou porta, permitindo um ajuste ideal para diferentes necessidades de vedação. 
O sistema é composto por tiras de PVC suspensas na vertical, fixadas em um perfil de aço inox na parte superior do vão-luz. Esse design possibilita uma fácil manutenção e remoção para limpeza, garantindo durabilidade e higiene no ambiente.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/c0d0b498414645a1b9718b28e824510b.jpg', '5.1.3.1', '5.1.3.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (11, 'Painel Térmico tipo PIR', 'Genérico - Portas', 'Porta Office Seco (POE)', 'Porta Isoplana - Office', 'A Porta Office White da Kingspan Isoeste é projetada para atender ambientes como escritórios, clínicas, escolas e módulos habitacionais, oferecendo alta resistência, design funcional e baixa manutenção. Disponível nas versões padrão e fixada em painel, adapta-se a diferentes projetos com exclusividades que garantem versatilidade e eficiência.
A versão padrão é indicada para instalação tradicional em vãos-luzes e proporciona flexibilidade de instalação, enquanto a versão fixada em painel é entregue já montada, simplificando a instalação e otimizando o tempo do projeto. Ambas possuem núcleo PIR AP, borracha de vedação para proteção contra poeira e redução de ruídos, além de maçaneta anti-enrosco que oferece segurança adicional.
Aplicações
  * Ideal para escritórios, módulos, containers, clínicas, escolas, hotéis e outros ambientes institucionais e comerciais. A versão fixada em painel é especialmente recomendada para projetos modulares que exigem instalação ágil.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/b056142ce6414d9fab82e9b2fff745d4.jpg', '5.1.3.11', '5.1.3.11-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (12, 'Painel Térmico tipo PIR', 'Genérico - Portas', 'Portinhola Óculo de Correr (BOE)', 'Portinhola Giratória', 'A Portinhola Giratória foi projetada para facilitar a passagem de pequenas mercadorias em ambientes controlados. Suas dimensões reduzidas contribuem para a redução da troca térmica durante a operação. O modelo é fornecido com fechadura padrão e abertura interna de segurança, favorecendo praticidade no uso.
Fabricada com núcleo em PIR AP e marco em alumínio, a portinhola está disponível em espessuras de 70, 100 e 150 mm, possibilitando diferentes configurações de acordo com a aplicação.
Aplicações
  * Indicada para câmaras frigoríficas e ambientes que demandam controle térmico, como indústrias alimentícias, supermercados, centros de distribuição e armazéns frigoríficos.

* Fornecedor referência Kinspan;
* Conferir em seu fornecedor as características e dimensões disponíveis;
* Imagens ilustrativas;', '/uploads/7e3be28a764241baadd30d59d8f23b7e.jpg', '5.1.3.4', '5.1.3.4-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (13, 'Válvula de Expansão', 'Carel', 'E2V, E3V e ExV', 'Válvula de Expansão Eletrônica', 'As válvulas de expansão eletrônica CAREL integram uma ampla família de componentes desenvolvidos para sistemas de refrigeração comercial, industrial e HVAC, atuando em conjunto com os controladores eletrônicos e plataformas de supervisão da fabricante para proporcionar controle preciso da alimentação de refrigerante nos evaporadores.
A linha contempla diferentes famílias e modelos, destacando-se as séries E2V, E3V e demais válvulas eletrônicas ExV, dimensionadas para diferentes capacidades frigoríficas e compatíveis com diversos fluidos refrigerantes, incluindo refrigerantes HFC, HFO e fluidos naturais, como o CO₂ em aplicações transcríticas.
Controladas por drivers eletrônicos e sensores de pressão e temperatura, as válvulas ajustam continuamente sua abertura em função da carga térmica do sistema, mantendo o superaquecimento dentro da faixa ideal de operação. Esse controle dinâmico proporciona melhor aproveitamento da superfície do evaporador, maior estabilidade operacional, redução do consumo de energia e proteção do compressor contra retorno de líquido.
A linha CAREL é amplamente aplicada em supermercados, frigoríficos, câmaras frigoríficas, chillers, centros logísticos, bombas de calor e processos industriais que demandam elevado desempenho, confiabilidade e precisão no controle da expansão do refrigerante.
', '/uploads/7b8f128c151643729d7b86d51140a5e2.jpg', '3.2.3.1', '3.2.3.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (14, 'Válvula de Expansão', 'FullGauge', 'SB', 'Válvula de Expansão Eletrônica', 'As válvulas de expansão eletrônica da Full Gauge Controls integram a plataforma de controle de expansão eletrônica da fabricante, desenvolvida para proporcionar elevado desempenho, precisão e eficiência energética em sistemas de refrigeração comercial e industrial. A solução é composta pelas válvulas eletrônicas da família SB e pelos controladores da linha VX, formando um sistema completo para gerenciamento do fluxo de refrigerante e controle do superaquecimento.
A família SB contempla modelos unipolares e bipolares, disponíveis em diversas capacidades, permitindo sua aplicação em equipamentos de pequeno, médio e grande porte. Projetadas para operar com elevada precisão, as válvulas ajustam continuamente a vazão de refrigerante conforme a demanda térmica do evaporador, proporcionando melhor aproveitamento da superfície de troca térmica, estabilidade operacional e maior eficiência do sistema frigorífico.
O controle das válvulas é realizado pelos controladores eletrônicos da família VX, que monitoram continuamente as condições de pressão e temperatura do sistema para calcular o superaquecimento em tempo real. A partir dessas informações, o controlador posiciona a válvula de forma precisa, mantendo as condições ideais de operação do evaporador, reduzindo o consumo de energia e protegendo o compressor contra retorno de líquido.
A solução é indicada para câmaras frigoríficas, supermercados, centrais frigoríficas, expositores refrigerados, ilhas de congelados, chillers e processos industriais que demandam controle preciso da expansão do refrigerante, elevada eficiência energética e integração com sistemas modernos de automação.', '/uploads/6614653081d644849341b15e9dc6d555.jpg', '3.2.2.1', '3.2.2.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (15, 'Válvula de Expansão', 'Danfoss', 'T2', 'Válvula de Expansão Termostática', 'As válvulas de expansão termostáticas Danfoss constituem uma tradicional família de dispositivos mecânicos destinados ao controle da alimentação de refrigerante em evaporadores, oferecendo elevada confiabilidade, robustez e estabilidade operacional.
O portfólio da fabricante contempla diversas famílias, destacando-se as séries T2/TE2, TE5, TE12, TE20 e demais modelos desenvolvidos para diferentes capacidades frigoríficas, faixas de temperatura de evaporação e tipos de refrigerantes.
Seu princípio de funcionamento baseia-se no controle mecânico do superaquecimento por meio do bulbo termostático instalado na saída do evaporador, ajustando automaticamente o fluxo de refrigerante conforme as condições de operação do sistema. Essa solução dispensa alimentação elétrica e proporciona excelente estabilidade mesmo em aplicações severas.
A ampla disponibilidade de orifícios intercambiáveis, elementos termostáticos e configurações construtivas permite selecionar a válvula mais adequada para cada projeto, atendendo desde pequenas unidades condensadoras até grandes instalações de refrigeração comercial e industrial.
Reconhecidas pela elevada durabilidade e simplicidade de manutenção, as válvulas termostáticas Danfoss continuam sendo amplamente empregadas em câmaras frigoríficas, supermercados, sistemas de ar-condicionado, centrais frigoríficas, processos industriais e diversas aplicações onde se busca confiabilidade, facilidade de manutenção e excelente desempenho operacional.', '/uploads/54fd0133162749e9840a1549d492fab5.jpg', '3.1.1.1', '3.1.1.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (16, 'Válvula de Expansão', 'Danfoss', 'ETS', 'Válvula de Expansão Eletrônica', 'As válvulas de expansão eletrônica Danfoss fazem parte de uma das mais completas linhas de controle de expansão disponíveis para sistemas de refrigeração e climatização, sendo amplamente utilizadas em aplicações comerciais, industriais e HVAC.
A família contempla as séries ETS, destinadas a aplicações de média e grande capacidade, além de outras soluções eletrônicas específicas para diferentes faixas de operação e fluidos refrigerantes. Em conjunto com os controladores eletrônicos de superaquecimento da Danfoss, essas válvulas proporcionam controle extremamente preciso da alimentação de refrigerante ao evaporador.
O acionamento é realizado por motores de passo de alta resolução, permitindo posicionamento preciso e resposta rápida às variações de carga térmica. Como resultado, obtém-se melhor aproveitamento da superfície de troca térmica do evaporador, redução do consumo energético, aumento da capacidade frigorífica útil e maior proteção do compressor.
A linha é compatível com diversos refrigerantes convencionais e naturais, incluindo aplicações com CO₂, amônia e HFOs, estando disponível em diferentes capacidades e configurações para atender desde pequenos sistemas até grandes centrais frigoríficas.
Essas válvulas são amplamente empregadas em supermercados, centrais frigoríficas, chillers, indústrias alimentícias, centros logísticos e processos industriais que exigem elevado desempenho e confiabilidade.', '/uploads/ba84c2e583624a31a9099019c1e05bb3.jpg', '3.2.1.1', '3.2.1.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (17, 'Gerenciamento', 'Carel', 'pRack', 'Sistema de Controle para Rack Paralelo', 'A família pRack representa a solução da CAREL destinada ao gerenciamento de centrais frigoríficas com compressores em paralelo. Esses controladores constituem o núcleo operacional do rack, sendo responsáveis pelo controle dos compressores, ventiladores dos condensadores, pressões de sucção e descarga, inversores de frequência e estratégias avançadas de eficiência energética.
O gerenciamento inteligente da capacidade frigorífica permite modular automaticamente a operação dos compressores e ventiladores conforme a demanda térmica da instalação, reduzindo partidas, aumentando a vida útil dos equipamentos e proporcionando significativa economia de energia.
Entre seus recursos destacam-se sucção flutuante (Floating Suction Pressure), condensação flutuante (Floating Condensing Pressure), gerenciamento de compressores com inversor de frequência, rotação automática dos compressores, gerenciamento de alarmes, registro histórico e comunicação através de protocolos industriais como Modbus e BACnet.
Sua aplicação é indicada para supermercados, atacarejos, centros de distribuição, frigoríficos, indústrias alimentícias e demais instalações que utilizem centrais frigoríficas de média e grande capacidade.', '/uploads/71f9b01baf6b487fafe47de6ccb80eb9.jpg', '1.3.2.3.1', '1.3.2.3.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (18, 'Gerenciamento', 'FullGauge', 'RCK', 'Sistema de Controle para Rack Paralelo', 'A solução Full Gauge Controls para gerenciamento de racks paralelos foi desenvolvida para oferecer controle preciso e supervisão completa de centrais frigoríficas, reunindo em um único sistema o gerenciamento dos compressores, ventiladores dos condensadores, pressões de sucção e descarga, dispositivos auxiliares e comunicação com o sistema supervisório Sitrad.
Os controladores da linha RCK realizam o gerenciamento automático da capacidade frigorífica da central, controlando o acionamento sequencial dos compressores e ventiladores conforme a carga térmica da instalação. Essa estratégia proporciona maior estabilidade operacional, reduz o consumo de energia e aumenta a vida útil dos equipamentos.
O sistema permite o controle de compressores de velocidade fixa e variável, gerenciamento de inversores de frequência, rotação automática entre compressores, controle de condensação, monitoramento das pressões de sucção e descarga, alarmes de segurança e proteção contra condições anormais de operação.
A comunicação através de duas portas RS-485 independentes permite integração com o software supervisório Sitrad e também com sistemas de automação utilizando protocolo Modbus, possibilitando monitoramento remoto, armazenamento de históricos, emissão de relatórios e gerenciamento centralizado da instalação.
Entre os recursos disponíveis destacam-se registro histórico das variáveis operacionais, tendências gráficas, gerenciamento de alarmes, acesso remoto para manutenção, atualização de firmware, backup de parâmetros e facilidade de comissionamento, proporcionando elevada confiabilidade operacional e redução dos custos de manutenção.
A solução é indicada para supermercados, centrais frigoríficas comerciais, atacarejos, centros logísticos, frigoríficos e instalações industriais que utilizam racks paralelos de compressores, oferecendo elevada eficiência energética, flexibilidade de configuração e integração com sistemas modernos de automação.', '/uploads/639bdd1c770b4471847cc011f022c037.jpg', '1.3.2.2.1', '1.3.2.2.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (19, 'Supervisão', 'FullGauge', 'Sitrad Pro', 'Sistema de Supervisão de Refrigeração', 'O Sitrad Pro é a plataforma de supervisão desenvolvida pela Full Gauge Controls para gerenciamento centralizado de instalações de refrigeração, climatização, aquecimento e automação. Constitui o nível superior da arquitetura de automação da fabricante, reunindo em uma única plataforma todos os equipamentos da família Full Gauge.
O sistema integra controladores de rack paralelo da linha RCK, controladores de temperatura das famílias MT, TC e demais linhas de refrigeração, controladores para válvulas de expansão eletrônica, controladores de degelo, pressão, umidade e diversos outros dispositivos da instalação, permitindo supervisão completa da planta.
Por meio do Sitrad Pro é possível acompanhar em tempo real temperaturas, pressões, estados operacionais, alarmes, consumo energético, históricos de operação e demais variáveis do processo. O sistema permite ainda alteração remota de parâmetros, armazenamento de históricos, emissão de relatórios e envio automático de notificações para equipes de operação e manutenção.
A comunicação ocorre através de redes RS-485 utilizando protocolo Modbus, além de recursos para acesso remoto via internet, possibilitando gerenciamento da instalação a partir de qualquer local autorizado.
Sua interface gráfica apresenta sinóticos da instalação, gráficos de tendências, controle de usuários, registro histórico e ferramentas para análise de desempenho, permitindo maior disponibilidade operacional dos equipamentos e redução dos custos de manutenção.', '/uploads/461f2f8492a843b79b65033dcf5d8b91.jpg', '1.2.3.2.1', '1.2.3.2.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (20, 'Supervisão', 'Carel', 'Boss, Plant Visor e Plant Watch', 'Sistema de Supervisão de Refrigeração', 'Os sistemas de supervisão da CAREL fazem parte da plataforma de automação desenvolvida para aplicações de refrigeração comercial, industrial e HVAC, atuando como o nível superior de gerenciamento da instalação. Soluções como Boss, PlantVisor e PlantWatch centralizam as informações provenientes dos diversos controladores da família CAREL, formando um sistema integrado para monitoramento, operação e gestão de toda a planta.
Integrados aos controladores de rack paralelo pRack, aos controladores de evaporadores da família MPX, aos controladores universais IR33, às válvulas de expansão eletrônica E2V e E3V, bem como a diversos dispositivos de campo, os supervisórios CAREL permitem que todos os equipamentos operem de forma coordenada, proporcionando maior eficiência energética, confiabilidade operacional e facilidade de manutenção.
A plataforma possibilita a visualização em tempo real das principais variáveis do processo, como temperaturas, pressões, umidade, estados operacionais, alarmes, consumo energético e condições de funcionamento dos equipamentos. Através de uma interface gráfica intuitiva, operadores e equipes de manutenção podem acompanhar toda a instalação localmente ou remotamente, reduzindo significativamente o tempo de resposta diante de ocorrências.
Outro importante diferencial é a capacidade de armazenamento histórico de dados (Data Logging), permitindo análises de desempenho, rastreabilidade de eventos, elaboração de relatórios e atendimento aos requisitos de qualidade exigidos por segmentos como indústria alimentícia, farmacêutica, centros logísticos e varejo.
Os sistemas de supervisão CAREL possuem arquitetura aberta e ampla compatibilidade com protocolos industriais, como Modbus, BACnet e outros padrões amplamente utilizados em automação predial e industrial, facilitando sua integração com sistemas de terceiros.
Entre suas funcionalidades destacam-se o gerenciamento centralizado de alarmes, programação remota de parâmetros, acesso seguro via rede, geração automática de relatórios, análise de tendências, otimização energética e suporte à manutenção preventiva baseada em dados operacionais.', '/uploads/9db9be4dfa754cc3ac17abe3ae416bfc.jpg', '1.2.3.3.1', '1.2.3.3.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (21, 'Controle Simples', 'FullGauge', 'MT-LT', 'Controladores de Temperatura', 'A linha MT/LT da Full Gauge Controls foi desenvolvida para oferecer controle preciso e confiável da temperatura em aplicações de refrigeração comercial e industrial, atendendo desde pequenos equipamentos até câmaras frigoríficas, balcões refrigerados, expositores e sistemas de conservação de alimentos.
Os controladores dessa família integram funções de acionamento do compressor, gerenciamento de degelo, controle dos ventiladores do evaporador, alarmes de temperatura, proteção dos equipamentos e diversas parametrizações operacionais, proporcionando elevado desempenho e facilidade de instalação.
Projetados para operação local, os equipamentos da linha MT/LT são ideais para aplicações que não demandam integração com sistemas supervisórios, mantendo a simplicidade de configuração e elevada confiabilidade operacional características da Full Gauge Controls.
A ampla disponibilidade de modelos permite selecionar o controlador mais adequado para cada aplicação, oferecendo soluções para refrigeração positiva, congelados, climatização e processos industriais, sempre com foco na estabilidade térmica, economia de energia e proteção dos produtos armazenados.', '/uploads/5cfa06db211c4fa29a9ffaeb9f6b5c6f.jpg', '1.2.1.2.1', '1.2.1.2.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (22, 'Gerenciamento', 'FullGauge', 'PCT-410E Plus', 'Sistema de Controle para Rack Paralelo', 'O PCT-410E Plus é um controlador digital de pressão da linha de pressostatos da Full Gauge, desenvolvido para controlar os estágios de sucção e descarga em centrais de refrigeração. Dependendo da configuração, ele pode controlar até 5 compressores e 5 ventiladores, utilizando sensores de pressão (4–20 mA), sensor de temperatura e uma saída analógica para controle de inversor de frequência. Também possui comunicação RS-485 para integração com o Sitrad Pro.
Sua aplicação típica é:
  * Controle de pressão de sucção;
  * Controle de pressão de descarga;
  * Acionamento sequencial de compressores;
  * Controle de ventiladores do condensador;
  * Controle proporcional por inversor de frequência;
  * Supervisão via Sitrad Pro.', '/uploads/b5aaf2a07af444119cb66b004c001e75.jpg', '1.3.2.2.2', '1.3.2.2.2-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (23, 'Controle Simples', 'Carel', 'IR33', 'Controladores de Temperatura', 'A família IR33 constitui uma das linhas mais tradicionais de controladores eletrônicos da CAREL, desenvolvida para aplicações em refrigeração comercial, climatização e processos industriais. Reconhecidos pela elevada confiabilidade e flexibilidade de configuração, esses controladores oferecem controle preciso da temperatura e diversas funções voltadas à proteção e ao desempenho dos sistemas frigoríficos.
Os equipamentos da família IR33 incorporam controle de compressor, gerenciamento automático de degelo, ventiladores, alarmes, proteção dos equipamentos e diversas estratégias de controle adaptáveis às mais variadas aplicações.
A família contempla versões para operação local e modelos com comunicação serial RS-485 e protocolo Modbus, permitindo integração aos sistemas supervisórios PlantVisor, PlantWatch e Boss, além de sistemas de automação predial e industrial. Essa flexibilidade permite que o mesmo controlador seja utilizado tanto em aplicações independentes quanto em instalações totalmente supervisionadas.
Amplamente utilizados em câmaras frigoríficas, vitrines refrigeradas, balcões frigoríficos, unidades condensadoras e diversos equipamentos de refrigeração comercial, os controladores IR33 combinam robustez, facilidade de programação e integração com a plataforma completa de automação da CAREL.', '/uploads/5954925d1d52439d8ec72d22f3a9e8fd.jpg', '1.2.1.3.1', '1.2.1.3.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (24, 'Controle + Acesso Remoto', 'Fullgauge', 'MT-LT Log', 'Controladores de Temperatura', 'A linha MT/LT Log representa a evolução da tradicional família de controladores Full Gauge, incorporando recursos de comunicação serial RS-485 com protocolo Modbus para integração aos sistemas de supervisão da fabricante.
Além de todas as funções de controle de temperatura, compressor, degelo, ventilação e alarmes presentes na linha convencional, os modelos Log permitem comunicação direta com o supervisório Sitrad Pro, possibilitando monitoramento remoto, alteração de parâmetros, registro histórico de temperaturas, emissão de relatórios, gerenciamento centralizado de alarmes e acompanhamento operacional em tempo real.
Essa integração transforma o controlador em parte de uma plataforma completa de automação, permitindo que instalações com diversos equipamentos sejam monitoradas de forma centralizada, reduzindo custos de manutenção, aumentando a rastreabilidade operacional e proporcionando maior disponibilidade dos sistemas frigoríficos.
A linha é indicada para supermercados, centros logísticos, câmaras frigoríficas, indústrias alimentícias e demais aplicações que exijam monitoramento contínuo, registro de dados e integração com sistemas supervisórios.', '/uploads/92b9d06f3faa4c09838d4bff07d073b5.jpg', '1.2.2.2.1', '1.2.2.2.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (25, 'Rack Paralelo', 'Genérico', 'Rack Paralelo S/ Carenagem', 'Rack Paralelo sem Carenagem', 'O rack de refrigeração será montado sobre base metálica estrutura e carenagens com espessura mínima de 1,25mm. Será revestido por pintura epóxi sem solventes e categoria naval com intuito de amenizar a ação corrosiva ambiente. As portas são planejadas para que o acesso ao interior do equipamento seja facilitado para manutenções e vedadas para evitar o menor contato possível do ar externo com as peças internas. O quadro elétrico terá porta dupla para proteção contra jatos d’agua e menor contato possível dos componentes com o ambiente externo. O rack também contará com bandeja coletora para que todos os fluídos que por ventura sejam expurgados dentro da carenagem, ou até mesmo água proveniente de limpeza sejam canalizados e despejados em rede adequada. ', '/uploads/f532ef027c9e4b6dacd2257d718b7151.png', '4.1.2.1.2.1', '4.1.2.1.2.1-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (26, 'Porta Frigorífica', 'Genérico - Portas', 'Porta Sala Limpa Isoplana Correr (PSC)', 'Porta Isoplana - Sala Limpa', 'A Porta de Correr Sala Limpa foi desenvolvida para ambientes que demandam controle de higiene e otimização de espaço. Fabricada com trilhos de alumínio anodizado e puxadores em aço inox, é leve e de fácil manuseio. O sistema deslizante favorece a utilização em locais onde a economia de espaço é um requisito.

Com núcleo em PIR AP e marco em alumínio, a porta pode contribuir para o desempenho térmico e auxiliar em ambientes com controle de temperatura e pressão.

Aplicações
Indicada para escritórios, clínicas, hospitais, salas limpas, aeroportos e escolas. Sua configuração deslizante pode favorecer a eficiência do espaço, ao mesmo tempo em que contribui para os requisitos de higiene de ambientes controlados.', '/uploads/8a1bf3de8174423da4047466e32de27e.jpg', '5.1.3.10', '5.1.3.10-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (27, 'Elétrica', 'Genérico', 'Genérico', 'Quadro de comando das câmaras – Centralizado (QL)', 'O quadro de linhas centralizado é uma solução destinada à organização, distribuição e controle das principais linhas frigoríficas de uma instalação, reunindo em um único ponto os componentes necessários para a interligação e o gerenciamento dos circuitos de refrigeração. A centralização dos elementos facilita a identificação das linhas, a operação do sistema e a execução de procedimentos de inspeção e manutenção.
O conjunto pode ser configurado de acordo com as características e necessidades de cada instalação, contemplando as linhas de líquido, sucção, descarga e demais circuitos frigoríficos previstos em projeto, bem como os respectivos componentes de bloqueio, controle, proteção e instrumentação. A disposição organizada dos componentes proporciona maior padronização da instalação e facilita futuras intervenções, ampliações ou modificações do sistema.
A montagem é realizada de forma a proporcionar acesso adequado aos componentes, identificação das linhas e organização das conexões, evitando cruzamentos desnecessários e facilitando a leitura do circuito frigorífico. A configuração do quadro deve considerar os diâmetros das tubulações, pressões e temperaturas de operação, tipo de refrigerante, vazões e características específicas de cada circuito.
Quando aplicado em instalações industriais, o quadro de linhas centralizado contribui para reduzir a quantidade de intervenções diretamente sobre as tubulações instaladas em campo, concentrando operações de bloqueio, manutenção e inspeção em uma região previamente definida. Essa característica proporciona maior organização ao sistema e pode reduzir o tempo necessário para determinadas intervenções de manutenção.
', '/uploads/f5196b6177ca4b668c537a562a82fcff.jpg', '1.1.3', '1.1.3-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (28, 'Elétrica', 'Genérico', 'Genérico', 'Quadro de comando das câmaras – Distribuído (QD)', 'O quadro de controle distribuído é uma solução compacta destinada à alimentação, proteção, comando e controle individual de cada ambiente frigorificado. Instalado próximo à respectiva câmara ou equipamento, reúne em um único conjunto os dispositivos elétricos e o controlador eletrônico responsável pelo gerenciamento da temperatura, degelo, ventilação e demais funções do sistema.
Seu formato modular facilita a instalação, identificação e manutenção dos circuitos, permitindo que cada ambiente opere de forma independente e com seus próprios parâmetros de controle. É uma solução prática e padronizada, amplamente utilizada em câmaras frigoríficas comerciais e industriais, podendo incorporar dispositivos de proteção, contatores, relés, bornes e controladores.
', '/uploads/db69a412203d4873a59e069024670ab3.jpg', '1.1.3', '1.1.3-2');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (29, 'Textos Comerciais', 'Genérico', 'Genérico', 'Suportes de tubulação e infraestrutura elétrica', 'Suporte de apoio e fixação da infraestrutura elétrica, tubulação de refrigeração e seu isolamento.
A base e/ou estruturas para os suportes são responsabilidade do cliente e devem estar a menos de 40 cm da passagem da tubulação e/ou eletrocalhas.
', '/uploads/eca172cde659433cb40b32ba20128e36.jpg', '7.1.7', '7.1.7-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (30, 'Textos Comerciais', 'Genérico', 'Genérico', 'Isolamento da tubulação – Espuma Elastomérica', 'O isolamento térmico das tubulações frigoríficas com espuma elastomérica de células fechadas é uma solução amplamente empregada em sistemas de refrigeração comercial e industrial para minimizar as trocas de calor entre o fluido refrigerante e o ambiente externo. O material apresenta baixa condutividade térmica e elevada resistência à difusão de vapor de água, características especialmente importantes em linhas que operam com temperaturas inferiores à ambiente, nas quais a entrada de umidade no isolamento pode provocar condensação, formação de gelo e degradação progressiva do desempenho térmico.
O isolamento é aplicado de forma contínua sobre as tubulações, envolvendo as linhas de sucção, líquido, descarga e demais trechos que necessitem de proteção térmica, com espessura definida de acordo com a temperatura de operação, diâmetro da tubulação, condições ambientais e requisitos de controle de condensação. As juntas e emendas devem ser cuidadosamente executadas e seladas, garantindo a continuidade da barreira de vapor e evitando a infiltração de umidade.
A espuma elastomérica apresenta ainda boa flexibilidade, permitindo sua aplicação em curvas, derivações e diferentes configurações de instalação sem comprometer a continuidade do isolamento. Quando corretamente dimensionado e instalado, o sistema reduz ganhos térmicos indesejados, contribui para a estabilidade das condições de operação do circuito frigorífico, evita a formação de condensação nas superfícies externas e auxilia na redução do consumo energético da instalação.
Em ambientes sujeitos à umidade elevada, intempéries, impactos mecânicos ou agentes externos, o isolamento deverá receber proteção superficial compatível com as condições de instalação. A execução deverá preservar a integridade do material e impedir a ocorrência de pontos de descontinuidade, esmagamento ou infiltração de umidade, garantindo a durabilidade e o desempenho do conjunto.

', '/uploads/f404f372429b46a0b542e10832d80d04.jpg', '7.1.4.3', '7.1.4.3-1');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (31, 'Textos Comerciais', 'Genérico', 'Genérico', 'Isolamento da tubulação – Poliuretano Injetado em Alumínio', 'O isolamento térmico das tubulações frigoríficas por meio de poliuretano injetado, encapsulado em revestimento de alumínio, constitui uma solução de elevado desempenho para instalações industriais que demandam baixa transferência de calor, elevada durabilidade e proteção mecânica e ambiental do isolamento. O sistema é particularmente adequado para redes frigoríficas de maior extensão, instalações industriais e tubulações expostas a condições severas de operação.
O isolamento é constituído por uma camada de espuma rígida de poliuretano (PU), obtida por injeção e conformação diretamente ao redor da tubulação, proporcionando elevada aderência e preenchimento uniforme do espaço destinado ao isolamento. A baixa condutividade térmica do poliuretano permite obter excelente desempenho com espessuras relativamente reduzidas, minimizando os ganhos ou perdas térmicas ao longo das linhas frigoríficas.
Externamente, o conjunto recebe revestimento de alumínio, responsável pela proteção mecânica e pela redução da exposição do isolamento à umidade, radiação solar, impactos e demais agentes presentes no ambiente de instalação. O acabamento metálico proporciona ainda elevada resistência e facilidade de higienização, sendo especialmente interessante em instalações industriais nas quais a durabilidade e a aparência da rede são requisitos do projeto.
A execução deverá garantir a continuidade do isolamento em todo o percurso da tubulação, incluindo curvas, derivações, suportes, válvulas e demais componentes, evitando pontes térmicas e regiões suscetíveis à condensação. As emendas e terminações do revestimento de alumínio deverão ser adequadamente executadas e vedadas, impedindo a penetração de água e umidade para o interior do sistema.
O dimensionamento da espessura do poliuretano deverá considerar a temperatura de operação da linha, temperatura e umidade do ambiente, diâmetro da tubulação, condição de instalação e temperatura superficial admissível. Para linhas de baixa temperatura, deverá ser dada especial atenção à continuidade da barreira de vapor, uma vez que a penetração de umidade no isolamento reduz significativamente seu desempenho térmico e pode provocar degradação prematura do sistema.
A solução em poliuretano injetado com acabamento em alumínio proporciona, portanto, uma combinação de elevado desempenho térmico, resistência mecânica, proteção contra intempéries e longa vida útil, sendo indicada para redes frigoríficas industriais e demais aplicações em que a confiabilidade e a durabilidade do isolamento sejam requisitos fundamentais do projeto.

', '/uploads/60ae2e196d3e487fa6700cfcc0a2d896.jpg', '7.1.4.3', '7.1.4.3-2');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (32, 'Textos Comerciais', 'Genérico', 'Genérico', 'Infraestrutura elétrica', 'A instalação elétrica deverá ser executada conforme a ABNT NBR 5410, utilizando materiais certificados e dimensionados de acordo com a capacidade de condução de corrente, queda de tensão, proteção contra sobrecorrentes e condições de instalação. Os condutores deverão possuir seção adequada à carga, isolação compatível com a tensão e temperatura de operação e identificação conforme a norma.
Os cabos deverão ser instalados de forma organizada em eletrocalhas, leitos ou eletrodutos, conforme a aplicação, mantendo separação e ocupação adequadas, proteção mecânica e facilidade de inspeção e manutenção. As eletrocalhas deverão possuir dimensões compatíveis com a quantidade de cabos, permitindo dissipação térmica e futuras ampliações, enquanto os eletrodutos deverão ser dimensionados de modo a não exceder sua taxa de ocupação e permitir o lançamento e a substituição dos condutores.
As instalações deverão contemplar condutor de proteção (PE), equipotencialização e identificação dos circuitos, além dos dispositivos de proteção e seccionamento previstos em projeto. Em ambientes frigorificados ou sujeitos à umidade, os materiais e respectivos graus de proteção deverão ser compatíveis com as condições ambientais, garantindo segurança, durabilidade e confiabilidade da instalação.', '/uploads/f0a8b540b3314bfc8afb029071700968.jpg', '7.1.7', '7.1.7-2');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (33, 'Textos Comerciais', 'Genérico', 'Genérico', 'Cabos de alimentação e comando', 'Os cabos de força serão utilizados na alimentação dos equipamentos frigoríficos e demais cargas elétricas da instalação, sendo dimensionados conforme corrente de projeto, método de instalação, queda de tensão, temperatura e condições ambientais, em atendimento à ABNT NBR 5410. Os cabos de sensores e controle serão destinados à interligação de sondas de temperatura, pressostatos, transdutores e demais dispositivos de instrumentação, utilizando condutores adequados ao sinal e à aplicação. A instalação será executada de forma organizada e protegida, mantendo a identificação dos circuitos e, quando necessário, a segregação entre cabos de potência e sinal para evitar interferências e garantir a confiabilidade dos sistemas de controle.', '/uploads/aa429f872c294169ac2cd3eb8623619c.jpg', '7.1.7', '7.1.7-3');
INSERT INTO "catalogo_comercial" ("id", "categoria", "fabricante", "modelo", "nome", "descricao_comercial", "imagem_path", "id_comercial", "id_cadastro") VALUES (34, 'Textos Comerciais', 'Genérico', 'Genérico', 'Rede de Drenagem', 'A rede de drenagem dos evaporadores será executada de acordo com a aplicação e a temperatura de operação de cada ambiente. Para câmaras de resfriados, serão utilizadas tubulações de PVC, dimensionadas para condução adequada da água proveniente da condensação e dos ciclos de degelo, sem necessidade de resistência elétrica. Para câmaras de congelados, a drenagem será executada em tubo de cobre, equipada com resistência elétrica de aquecimento, evitando o congelamento da água no interior da tubulação e garantindo o escoamento durante a operação e os ciclos de degelo. O sistema deverá possuir declividade adequada, conexões devidamente vedadas e instalação compatível com as condições de temperatura do ambiente. ', '/uploads/a3be2f5da0fe4f74bca91125cc18ae1f.png', '7.1.5.3', '7.1.5.3-1');