-- dados_climatologicos_inmet — bloco 1 de 1 (193 registros no total)

INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (1, '82915', 'RIO BRANCO', 'AC', 39.2, 85.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (2, '82807', 'TARAUACA', 'AC', 37.9, 85.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (3, '82989', 'AGUA BRANCA', 'AL', 37.2, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (4, '82994', 'MACEIO', 'AL', 35.8, 79.2);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (5, '82992', 'PALMEIRA DOS INDIOS', 'AL', 39.9, 74.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (6, '82996', 'PORTO DE PEDRAS', 'AL', 33.4, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (7, '82113', 'BARCELOS', 'AM', 39.3, 86.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (8, '82410', 'BENJAMIN CONSTANT', 'AM', 40.0, 86.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (9, '82326', 'CODAJAS', 'AM', 38.6, 85.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (10, '82610', 'EIRUNEPE', 'AM', 39.8, 84.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (11, '82212', 'FONTE BOA', 'AM', 38.0, 87.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (12, '82336', 'ITACOATIARA', 'AM', 39.1, 83.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (13, '82331', 'MANAUS', 'AM', 39.0, 81.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (14, '82106', 'SAO GABRIEL DA CACHOEIRA(UAUPES)', 'AM', 39.4, 87.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (15, '82317', 'TEFE', 'AM', 39.7, 87.2);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (16, '82098', 'MACAPA', 'AP', 39.1, 80.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (17, '83249', 'ALAGOINHAS', 'BA', 42.2, 79.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (18, '83179', 'BARRA', 'BA', 40.3, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (19, '83236', 'BARREIRAS', 'BA', 40.9, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (20, '83288', 'BOM JESUS DA LAPA', 'BA', 41.6, 59.5);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (21, '83498', 'CARAVELAS', 'BA', 37.2, 82.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (22, '83408', 'CARINHANHA', 'BA', 41.1, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (23, '83192', 'CIPO', 'BA', 42.0, 69.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (24, '83286', 'CORRENTINA', 'BA', 40.4, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (25, '83446', 'GUARATINGA', 'BA', 39.6, 78.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (26, '83182', 'IRECE', 'BA', 39.1, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (27, '83244', 'ITABERABA', 'BA', 40.1, 69.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (28, '83242', 'LENCOIS', 'BA', 39.8, 72.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (29, '83184', 'MORRO DO CHAPEU', 'BA', 35.0, 73.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (30, '82979', 'REMANSO', 'BA', 39.6, 62.4);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (31, '83229', 'SALVADOR (ONDINA)', 'BA', 37.1, 81.5);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (32, '83076', 'STa. R. DE CASSIA (IBIPETUBA)', 'BA', 41.6, 58.4);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (33, '83344', 'VITORIA DA CONQUISTA', 'BA', 35.0, 79.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (34, '82784', 'BARBALHA', 'CE', 39.2, 67.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (35, '82397', 'FORTALEZA', 'CE', 36.5, 77.5);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (36, '82487', 'GUARAMIRANGA', 'CE', 38.4, 86.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (37, '82493', 'JAGUARUANA', 'CE', 38.5, 71.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (38, '82588', 'MORADA NOVA', 'CE', 39.0, 73.22);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (39, '82586', 'QUIXERAMOBIM', 'CE', 38.4, 65.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (40, '82392', 'SOBRAL', 'CE', 39.8, 69.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (41, '82683', 'TAUA', 'CE', 39.4, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (42, '83377', 'BRASILIA', 'DF', 36.4, 64.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (43, '83557', 'BOA ESPERANCA', 'ES', 40.5, 73.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (44, '83546', 'ECOPORANGA', 'ES', 40.0, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (45, '83013', 'MUNIZ FREIRE', 'ES', 39.4, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (46, '83550', 'SAO MATEUS', 'ES', 38.7, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (47, '83648', 'VITORIA', 'ES', 39.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (48, '83368', 'ARAGARCAS', 'GO', 42.2, 68.2);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (49, '83526', 'CATALAO', 'GO', 38.8, 64.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (50, '83379', 'FORMOSA', 'GO', 37.9, 64.2);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (51, '83423', 'GOIANIA', 'GO', 41.2, 60.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (52, '83374', 'GOIAS', 'GO', 41.9, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (53, '83522', 'IPAMERI', 'GO', 39.3, 67.5);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (54, '83464', 'JATAI', 'GO', 39.8, 69.2);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (55, '83376', 'PIRENOPOLIS', 'GO', 39.8, 67.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (56, '83332', 'POSSE', 'GO', 38.3, 62.4);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (57, '82970', 'ALTO PARNAIBA', 'MA', 41.0, 72.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (58, '82460', 'BACABAL', 'MA', 41.5, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (59, '82768', 'BALSAS', 'MA', 40.2, 67.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (60, '82571', 'BARRA DO CORDA', 'MA', 40.1, 73.2);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (61, '82765', 'CAROLINA', 'MA', 40.9, 71.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (62, '82382', 'CHAPADINHA', 'MA', 39.3, 74.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (63, '82676', 'COLINAS', 'MA', 40.8, 73.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (64, '82280', 'SAO LUIS', 'MA', 37.2, 82.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (65, '82198', 'TURIACU', 'MA', 35.9, 83.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (66, '82376', 'ZE DOCA', 'MA', 38.0, 75.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (67, '83442', 'ARACUAI', 'MG', 44.0, 61.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (68, '83579', 'ARAXA', 'MG', 36.9, 71.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (69, '83384', 'ARINOS', 'MG', 42.5, 62.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (70, '83582', 'BAMBUI', 'MG', 39.1, 78.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (71, '83587', 'BELO HORIZONTE', 'MG', 37.4, 63.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (72, '83533', 'BOM DESPACHO', 'MG', 39.9, 72.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (73, '83589', 'C. DO MATO DENTRO', 'MG', 39.1, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (74, '83514', 'CAPINOPOLIS', 'MG', 41.3, 68.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (75, '83592', 'CARATINGA', 'MG', 39.0, 75.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (76, '83485', 'CARBONITA', 'MG', 39.6, 68.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (77, '83538', 'DIAMANTINA', 'MG', 33.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (78, '83635', 'DIVINOPOLIS', 'MG', 39.2, 65.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (79, '83581', 'FLORESTAL', 'MG', 39.4, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (80, '83488', 'ITAMARANDIBA', 'MG', 37.5, 75.4);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (81, '83395', 'JANAUBA', 'MG', 41.8, 59.5);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (82, '83386', 'JANUARIA', 'MG', 41.6, 62.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (83, '83692', 'JUIZ DE FORA', 'MG', 37.4, 79.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (84, '83452', 'JURAMENTO', 'MG', 40.0, 70.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (85, '83687', 'LAVRAS', 'MG', 37.2, 71.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (86, '83683', 'MACHADO', 'MG', 37.1, 76.5);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (87, '83388', 'MONTE AZUL', 'MG', 41.1, 58.5);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (88, '83437', 'MONTES CLAROS', 'MG', 40.4, 63.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (89, '83479', 'PARACATU', 'MG', 40.2, 69.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (90, '83737', 'PASSA QUATRO', 'MG', 36.2, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (91, '83531', 'PATOS DE MINAS', 'MG', 37.9, 69.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (92, '83483', 'PIRAPORA', 'MG', 41.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (93, '83570', 'POMPEU', 'MG', 39.8, 65.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (94, '83441', 'SALINAS', 'MG', 41.3, 68.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (95, '83736', 'SAO LOURENCO', 'MG', 36.6, 75.4);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (96, '83586', 'SETE LAGOAS', 'MG', 39.7, 66.55);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (97, '83492', 'TEOFILO OTONI', 'MG', 41.3, 70.64);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (98, '83577', 'UBERABA', 'MG', 40.7, 68.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (99, '83428', 'UNAI', 'MG', 42.6, 63.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (100, '83642', 'VICOSA', 'MG', 37.6, 79.4);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (101, '83565', 'PARANAIBA', 'MS', 42.8, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (102, '83361', 'CUIABA', 'MT', 44.0, 73.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (103, '83309', 'DIAMANTINO', 'MT', 42.5, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (104, '83214', 'MATUPA', 'MT', 40.2, 79.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (105, '83319', 'NOVA XAV.(XAVANTINA)', 'MT', 43.9, 77.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (106, '83364', 'PADRE RICARDO REMETTER', 'MT', 43.2, 75.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (107, '83358', 'POXORÉU', 'MT', 44.5, 75.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (108, '82353', 'ALTAMIRA', 'PA', 39.2, 79.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (109, '82191', 'BELEM', 'PA', 37.2, 84.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (110, '82246', 'BELTERRA', 'PA', 37.1, 87.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (111, '82263', 'CAMETA', 'PA', 37.1, 83.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (112, '82861', 'CONCEICAO DO ARAGUAIA', 'PA', 41.7, 79.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (113, '82445', 'ITAITUBA', 'PA', 40.4, 85.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (114, '82562', 'MARABA', 'PA', 39.7, 75.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (115, '82181', 'MONTE ALEGRE', 'PA', 38.0, 72.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (116, '82178', 'OBIDOS', 'PA', 36.9, 83.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (117, '82184', 'PORTO DE MOZ', 'PA', 36.7, 83.2);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (118, '82145', 'TRACUATEUA', 'PA', 36.6, 85.2);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (119, '82361', 'TUCURUI', 'PA', 38.9, 81.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (120, '82795', 'CAMPINA GRANDE', 'PB', 34.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (121, '82798', 'JOAO PESSOA', 'PB', 34.3, 76.2);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (122, '82791', 'PATOS', 'PB', 39.8, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (123, '82890', 'ARCOVERDE', 'PE', 37.4, 76.4);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (124, '82886', 'CABROBO', 'PE', 40.0, 56.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (125, '82753', 'OURICURI', 'PE', 38.8, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (126, '82983', 'PETROLINA', 'PE', 40.2, 55.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (127, '82900', 'RECIFE (CURADO)', 'PE', 34.8, 77.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (128, '82797', 'SURUBIM', 'PE', 36.5, 76.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (129, '82975', 'BOM JESUS DO PIAUI', 'PI', 44.7, 51.5);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (130, '82976', 'CARACOL', 'PI', 38.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (131, '82678', 'FLORIANO', 'PI', 41.8, 63.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (132, '82287', 'PARNAIBA', 'PI', 38.8, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (133, '82882', 'PAULISTANA', 'PI', 40.8, 57.65);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (134, '82480', 'PIRIPIRI', 'PI', 41.0, 68.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (135, '82879', 'SAO JOAO DO PIAUI', 'PI', 41.2, 56.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (136, '82578', 'TERESINA', 'PI', 41.1, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (137, '82870', 'VALE DO GURGUEIA (CRISTIANO CASTRO)', 'PI', 41.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (138, '83842', 'CURITIBA', 'PR', 35.4, 80.5);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (139, '83836', 'IRATI', 'PR', 35.6, 80.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (140, '83766', 'LONDRINA', 'PR', 40.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (141, '83767', 'MARINGA', 'PR', 40.4, 68.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (142, '83007', 'ALTO DA BOA VISTA', 'RJ', 38.5, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (143, '83049', 'AVELAR (P.DO ALFERES)', 'RJ', 39.1, 78.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (144, '83698', 'CAMPOS', 'RJ', 41.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (145, '83807', 'CARMO', 'RJ', 40.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (146, '83718', 'CORDEIRO', 'RJ', 38.7, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (147, '83114', 'IGUABA GRANDE', 'RJ', 40.3, 76.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (148, '83695', 'ITAPERUNA', 'RJ', 42.0, 73.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (149, '83738', 'RESENDE', 'RJ', 39.0, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (150, '83696', 'SANTA MARIA MADALENA', 'RJ', 39.1, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (151, '83805', 'SANTO ANTONIO DE PADUA', 'RJ', 41.5, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (152, '83744', 'TERESOPOLIS', 'RJ', 36.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (153, '82596', 'CEARA MIRIM', 'RN', 35.4, 79.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (154, '82693', 'CRUZETA', 'RN', 39.1, 59.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (155, '82598', 'NATAL', 'RN', 34.0, 80.5);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (156, '82024', 'BOA VISTA', 'RR', 42.0, 75.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (157, '82042', 'CARACARAI', 'RR', 38.8, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (158, '83980', 'BAGE', 'RS', 41.1, 72.4);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (159, '83919', 'BOM JESUS', 'RS', 33.8, 79.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (160, '83942', 'CAXIAS DO SUL', 'RS', 35.0, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (161, '83912', 'CRUZ ALTA', 'RS', 38.0, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (162, '83964', 'ENCRUZILHADA DO SUL', 'RS', 37.9, 76.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (163, '83914', 'PASSO FUNDO', 'RS', 36.4, 72.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (164, '83985', 'PELOTAS', 'RS', 39.8, 82.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (165, '83967', 'PORTO ALEGRE', 'RS', 40.6, 76.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (166, '83936', 'SANTA MARIA', 'RS', 40.2, 78.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (167, '83997', 'SANTA VITORIA DO PALMAR', 'RS', 39.9, 80.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (168, '83907', 'SAO LUIZ GONZAGA', 'RS', 40.1, 71.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (169, '83948', 'TORRES', 'RS', 41.4, 83.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (170, '83927', 'URUGUAIANA', 'RS', 40.6, 72.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (171, '83887', 'CAMPOS NOVOS', 'SC', 33.7, 76.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (172, '83883', 'CHAPECO', 'SC', 37.7, 73.4);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (173, '83897', 'FLORIANOPOLIS', 'SC', 40.0, 79.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (174, '83872', 'INDAIAL', 'SC', 41.2, 85.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (175, '83891', 'LAGES', 'SC', 34.5, 80.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (176, '83920', 'SAO JOAQUIM', 'SC', 30.0, 82.2);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (177, '83096', 'ARACAJU', 'SE', 35.3, 75.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (178, '83195', 'ITABAIANINHA', 'SE', 38.9, 80.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (179, '83097', 'PROPRIA', 'SE', 39.8, 75.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (180, '83714', 'CAMPOS DO JORDAO', 'SP', 29.7, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (181, '83676', 'CATANDUVA', 'SP', 42.5, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (182, '83630', 'FRANCA', 'SP', 37.8, 68.3);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (183, '83726', 'SAO CARLOS', 'SP', 37.9, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (184, '83781', 'SAO PAULO (MIR.DE SANTANA)', 'SP', 37.8, 73.6);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (185, '83669', 'SAO SIMAO', 'SP', 41.3, 68.9);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (186, '82659', 'ARAGUAINA', 'TO', 38.8, 77.1);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (187, '83033', 'PALMAS', 'TO', 42.3, 67.8);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (188, '82863', 'PEDRO AFONSO', 'TO', 40.9, 75.4);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (189, '83228', 'PEIXE', 'TO', 43.2, 69.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (190, '83235', 'TAGUATINGA', 'TO', 40.6, 75.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (191, 'A940', 'ARIQUEMES', 'RO', 40.8, 78.0);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (192, 'A939', 'CACOAL', 'RO', 41.5, 75.7);
INSERT INTO "dados_climatologicos_inmet" ("id", "codigo", "nome_estacao", "uf", "temp_maxima_historica", "ur_media_historica") VALUES (193, 'A938', 'VILHENA', 'RO', 36.7, 83.0);