-- forcador_linhas — bloco 1 de 1 (13 registros no total)

INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (4, 1, 'FL', '04/2025', TRUE, NULL, NULL, 'Evaporador de baixo perfil destinado para armazenamentos de resfriados e congelados de setores como: Supermercados, restaurantes, hortifrútis, açougues, padarias, laticínios, farmacêuticos, hospitalares, indústrias, bebidas e processamento de alimentos. Características principais: dreno metálico, bandeja e laterais articuláveis e removíveis, suporte de fixação, pressurizado, grade plástica antichama (classificação v0) e hélice metálica, resistência elétrica no núcleo e na bandeja com fácil remoção.', '/uploads/7e057c2794eb4224957859a69c7f227f.png', '4.2.1.1');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (5, 1, 'EDH - 6 Aletas', '04/2025', TRUE, NULL, NULL, 'Evaporador com dupla saída de ar com 6 aletas por polegada e baixo nível de ruído para aplicações como sala de preparo, câmaras frigoríficas, corredores de recebimento de produtos e laboratórios. Características: Dreno metálico, bandeja articulável e laterais removíveis, suporte de fixação, tubo com plug de borracha pressurizado 30 psi e grade metálica.', '/uploads/d9e0a42b32b34007860c55648bdd8bc3.png', '4.2.1.2');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (6, 1, 'EDH - 4 Aletas', '04/2025', TRUE, NULL, NULL, 'Evaporador com dupla saída de ar com 4 aletas por polegada, degelo elétrico e baixo nível de ruído para aplicações como sala de preparo, câmaras frigoríficas, corredores de recebimento de produtos e laboratórios. Características: Dreno metálico, bandeja articulável e laterais removíveis, suporte de fixação, tubo com plug de borracha pressurizado 30 psi e grade metálica.', '/uploads/f7a1b9034cca4adb9802adcd70502c8a.png', '4.2.1.3');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (7, 1, 'FM*4', '04/2025', TRUE, NULL, NULL, 'Evaporador de médio perfil com 4 aletas por polegada destinado para armazenamentos de resfriados e congelados de setores como: Supermercados, restaurantes, hortifrútis, proteínas, laticínios, farmacêuticos, hospitalares, indústrias, bebidas e processamento de alimentos. Características: Bandeja articulável, laterais removíveis, suporte de fixação, tubo com plug de borracha pressurizado 30 psi, grade metálica.', '/uploads/ac52950627a742e7b88a05cead86a80f.png', '4.2.1.4');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (8, 1, 'FM*6', '04/2025', TRUE, NULL, NULL, 'Evaporador de médio perfil com 6 aletas por polegada destinado para armazenamentos de resfriados e congelados de setores como: Supermercados, restaurantes, hortifrútis, proteínas, laticínios, farmacêuticos, hospitalares, indústrias, bebidas e processamento de alimentos. Características: Bandeja articulável, laterais removíveis, suporte de fixação, tubo com plug de borracha pressurizado 30 psi, grade metálica.', '/uploads/e244f6e424f54aeb9143bc64c9fae58c.png', '4.2.1.5');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (10, 1, 'FBX+', '02/2025', TRUE, NULL, NULL, 'Evaporador de baixo perfil destinado para armazenamentos de resfriados e congelados de setores como: Supermercados, restaurantes, hortifrútis, açougues, padarias, laticínios, farmacêuticos, hospitalares, indústrias, bebidas e processamento de alimentos.
Características: Gabinete compacto, caixa elétrica plástica Elgin com mini borne mola, grade difusora, hélice plástica, dreno metálico, bandeja e laterais articuláveis e removíveis, suporte de fixação, tubo com plug de borracha pressurizado, resistência elétrica no núcleo e na bandeja.
', '/uploads/6de63fc6486540e8918566f044580086.jpg', '4.2.1.6');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (11, 1, 'FL+', '03/2025', TRUE, NULL, NULL, 'O Evaporador FL+ é destinado para armazenamentos de resfriados e congelados de setores como: Supermercados, restaurantes, hortifrútis, açougues, padarias, laticínios, farmacêuticos, hospitalares, indústrias, bebidas e processamento de alimentos. Possuem motores ventiladores axiais que proporciona uma maior capacidade frigorífica e maior vazão de ar sendo diferenciais para sua aplicação. Características: Dreno metálico, bandeja e laterais articuláveis e removíveis, suporte de fixação, tubo com plug de borracha pressurizado, grade e hélice metálica, resistência elétrica no núcleo e na bandeja. ', '/uploads/5a69e20f1be7422f8e91dff46eb3b22c.jpg', '4.2.1.7');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (12, 2, 'MI GS2', '01/2024', TRUE, NULL, NULL, 'Evaporador de ar baixo perfil com design inovador com acessos sem necessidade de ferramentas. Painel frontal com articulação mecânica à mola, para pleno acesso a higienização do bloco aletado e da bandeja, como também, aos ventiladores e ligações elétricas. Tampas laterais articuladas que permitem acesso rápido aos controles de refrigeração e ao painel elétrico. Abertura frontal sem necessidade de ferramentas. Bandeja de drenagem articulada e removível para sua perfeita higienização e do bloco aletado tornando ágil esta operação. Acesso para as resistências de degelo pela dianteira e pela traseira do equipamento para uma rápida inspeção e manutenção. Conexão de drenagem de água traseira para maximizar espaço da câmara, propicia uma instalação limpa e harmoniosa.', '/uploads/9bac3fcaeff242a89d7f8e33508f1a00.png', '4.2.2.1');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (15, 2, 'EVIB EC', '04/2024', TRUE, NULL, NULL, 'A linha de forçadores de ar EVIB EC da Mipal foi desenvolvida para aplicações em câmaras frigoríficas de baixa temperatura que exigem elevada eficiência energética, controle preciso da temperatura e máxima confiabilidade operacional. Equipada com ventiladores de tecnologia EC (Electronically Commutated), a linha alia alto desempenho frigorífico à redução do consumo de energia, proporcionando excelente relação entre produtividade, economia operacional e preservação dos produtos armazenados.
Projetados para operar em ambientes de congelamento e conservação de produtos a baixas temperaturas, os evaporadores EVIB EC utilizam serpentinas de alta eficiência, fabricadas com tubos de cobre e aletas de alumínio de elevada condutividade térmica. Seu projeto otimiza a transferência de calor, garantindo elevada capacidade frigorífica, rápida remoção da carga térmica e maior estabilidade da temperatura interna da câmara frigorífica.
O espaçamento entre as aletas é especialmente dimensionado para aplicações de baixa temperatura, reduzindo os efeitos do acúmulo de gelo sobre a serpentina e contribuindo para a manutenção da capacidade de troca térmica durante períodos prolongados de operação. Essa característica aumenta os intervalos entre os ciclos de degelo, reduz o consumo de energia e melhora o desempenho global do sistema de refrigeração.
Os ventiladores com motores EC representam um importante avanço tecnológico em relação aos motores convencionais. Sua elevada eficiência permite significativa redução do consumo de energia elétrica, enquanto o controle eletrônico da velocidade possibilita ajustar a vazão de ar conforme a demanda térmica da instalação. Essa modulação proporciona maior estabilidade da temperatura, menor nível de ruído, redução dos ciclos de partida e parada dos ventiladores e aumento da vida útil dos componentes eletromecânicos.
A distribuição uniforme do fluxo de ar favorece a homogeneidade térmica em toda a câmara frigorífica, reduzindo gradientes de temperatura e contribuindo para a conservação da qualidade, textura e características dos produtos armazenados. A circulação eficiente do ar também auxilia na redução da desidratação superficial dos produtos, aspecto fundamental em aplicações de congelamento e estocagem prolongada.
A linha EVIB EC foi projetada para operar com sistemas de degelo adequados às condições de baixa temperatura, garantindo rápida remoção do gelo acumulado na serpentina e rápido restabelecimento da capacidade frigorífica. A combinação entre serpentina otimizada, ventiladores de alta eficiência e gerenciamento adequado do degelo resulta em maior disponibilidade operacional e menores custos de operação ao longo da vida útil do equipamento.
Construídos com estrutura em chapas de aço galvanizado de elevada resistência à corrosão, os evaporadores EVIB EC oferecem robustez, durabilidade e facilidade de manutenção. Seu projeto permite acesso simplificado aos principais componentes, reduzindo o tempo necessário para inspeções, limpeza e manutenção preventiva.
Disponível em diversas capacidades frigoríficas, a linha EVIB EC atende câmaras frigoríficas de congelados, frigoríficos, indústrias alimentícias, centros de distribuição, supermercados, processadoras de carnes, pescados, alimentos congelados e demais aplicações industriais e comerciais que exigem elevado desempenho térmico aliado à máxima eficiência energética.
Aplicações
Os forçadores de ar da linha EVIB EC são recomendados para câmaras frigoríficas de congelados, túneis de congelamento, centros de distribuição refrigerados, frigoríficos, indústrias alimentícias, supermercados, processadoras de carnes, pescados e alimentos congelados, bem como outras aplicações de baixa temperatura que demandem elevada capacidade frigorífica, eficiência energética superior e controle preciso das condições de armazenamento.
', '/uploads/ba6db47dc3f3422593587b8b549b1f91.jpg', '4.2.2.3');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (16, 2, 'HdhB AC', '01/2023', TRUE, NULL, NULL, 'A linha de forçadores de ar HDHB da Mipal foi desenvolvida para aplicações de alta capacidade em câmaras frigoríficas e instalações industriais que exigem elevado desempenho na troca térmica, ampla circulação de ar e máxima confiabilidade operacional. Projetados para operar continuamente em condições severas, os evaporadores da linha HDHB oferecem alta eficiência frigorífica, robustez construtiva e excelente desempenho em sistemas de média e baixa temperatura.
Equipados com serpentinas de alta eficiência, fabricadas com tubos de cobre e aletas de alumínio de elevada condutividade térmica, os evaporadores proporcionam excelente transferência de calor, permitindo rápida remoção da carga térmica e maior estabilidade da temperatura no ambiente refrigerado. O dimensionamento otimizado da serpentina assegura elevado rendimento frigorífico, reduzindo perdas de capacidade e contribuindo para maior eficiência energética do sistema.
A linha HDHB utiliza ventiladores axiais de grande diâmetro e alto rendimento, capazes de proporcionar elevada vazão de ar com distribuição uniforme em toda a câmara frigorífica. Essa característica garante melhor homogeneidade da temperatura, reduz zonas de estagnação do ar e melhora a conservação dos produtos armazenados, especialmente em câmaras de grandes dimensões e elevada carga térmica.
Projetados para aplicações industriais, os equipamentos possuem estrutura reforçada em chapas de aço galvanizado com acabamento de elevada resistência à corrosão, suportando ambientes agressivos e operação contínua com elevada confiabilidade. Seu projeto facilita o acesso aos componentes internos, permitindo maior agilidade nas atividades de inspeção, limpeza e manutenção preventiva, reduzindo custos operacionais e aumentando a disponibilidade da instalação.
A linha HDHB pode ser equipada com sistemas de degelo adequados à aplicação, garantindo rápida remoção do gelo acumulado na serpentina e restabelecimento da capacidade frigorífica com menor tempo de parada. A correta seleção do sistema de degelo, associada ao espaçamento adequado entre as aletas, contribui para maior eficiência operacional, redução do consumo de energia e aumento da vida útil dos componentes.
Disponível em diversas capacidades frigoríficas e configurações construtivas, a linha HDHB atende aplicações em frigoríficos, centros de distribuição, indústrias alimentícias, câmaras de estocagem, túneis de resfriamento, centros logísticos refrigerados, laticínios, processadoras de carnes, pescados e demais processos industriais que demandam elevado desempenho térmico e 
Aplicações
Os forçadores de ar da linha HDHB são recomendados para câmaras frigoríficas de grande porte, centros de distribuição refrigerados, frigoríficos, indústrias alimentícias, laticínios, processadoras de carnes, pescados, alimentos congelados, centros logísticos, túneis de resfriamento e congelamento e demais aplicações industriais que exijam elevada capacidade frigorífica, distribuição uniforme do ar e máxima confiabilidade operacional.
', '/uploads/60c0fc9e8cdc4fdf910508290dbe27a5.jpg', '4.2.2.4');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (17, 2, 'HdhB EC', '01/2023', TRUE, NULL, NULL, 'A linha de forçadores de ar HDHB EC da Mipal reúne elevado desempenho frigorífico, eficiência energética e tecnologia de ventilação de última geração para aplicações industriais de média e baixa temperatura. Desenvolvida para atender instalações que exigem alta capacidade de troca térmica, controle preciso da temperatura e redução dos custos operacionais, a linha incorpora ventiladores com motores EC (Electronically Commutated), proporcionando maior rendimento, menor consumo de energia e excelente confiabilidade em operação contínua.
Projetados para aplicações de grande porte, os evaporadores HDHB EC utilizam serpentinas de alta eficiência fabricadas com tubos de cobre e aletas de alumínio, garantindo excelente transferência de calor e elevada capacidade frigorífica. O conjunto foi desenvolvido para proporcionar distribuição uniforme do fluxo de ar, reduzindo gradientes de temperatura no interior da câmara frigorífica e assegurando melhores condições de conservação dos produtos armazenados.
O principal diferencial da linha HDHB EC está na utilização de ventiladores equipados com motores eletronicamente comutados, tecnologia que combina a eficiência dos motores de corrente contínua com a praticidade da alimentação em corrente alternada. Essa solução permite significativa redução do consumo de energia elétrica quando comparada aos motores convencionais, além de possibilitar o controle eletrônico da velocidade de rotação conforme a demanda térmica da instalação.
A modulação da velocidade dos ventiladores proporciona maior estabilidade da temperatura ambiente, menor oscilação durante os ciclos de refrigeração e degelo, redução dos níveis de ruído e aumento da eficiência global do sistema frigorífico. A operação em velocidade variável também reduz o número de partidas bruscas, diminuindo esforços mecânicos e prolongando a vida útil dos componentes.
A estrutura dos evaporadores é construída em chapas de aço galvanizado de elevada resistência mecânica e proteção contra corrosão, garantindo longa vida útil mesmo em ambientes agressivos e de elevada umidade. Seu projeto facilita o acesso aos componentes internos, simplificando procedimentos de inspeção, limpeza e manutenção preventiva, reduzindo o tempo de parada e os custos de manutenção.
A linha HDHB EC pode ser aplicada em câmaras frigoríficas de grande porte, centros de distribuição refrigerados, frigoríficos, indústrias alimentícias, laticínios, processadoras de carnes e pescados, túneis de resfriamento e congelamento e demais aplicações industriais que demandam elevada capacidade frigorífica, eficiência energética e controle preciso das condições de operação.
Além da economia de energia proporcionada pelos motores EC, a correta seleção do evaporador, considerando capacidade frigorífica, diferencial de temperatura (TD), vazão de ar, temperatura de evaporação e sistema de degelo, contribui para otimizar o desempenho do sistema, aumentar o coeficiente de performance (COP) e reduzir os custos operacionais ao longo de toda a vida útil da instalação.
Aplicações
Os forçadores de ar HDHB EC são recomendados para sistemas de refrigeração comercial e industrial que buscam máxima eficiência energética, elevada confiabilidade operacional e controle preciso da temperatura, sendo indicados para câmaras frigoríficas de média e baixa temperatura, centros logísticos refrigerados, frigoríficos, indústrias alimentícias, supermercados, centros de distribuição e demais aplicações onde o desempenho térmico e a economia de energia são fatores essenciais.
', '/uploads/509bb24bbc2c4c31922728c629c70d27.jpg', '4.2.2.5');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (18, 2, 'EVIB AC - 6 Polos', '04/2024', TRUE, NULL, NULL, 'A linha de forçadores de ar EVIB da Mipal foi desenvolvida para aplicações em câmaras frigoríficas de baixa temperatura, onde a eficiência da troca térmica, a confiabilidade operacional e o controle preciso da temperatura são fatores determinantes para a conservação dos produtos armazenados. Projetada para operar com sistemas de degelo elétrico.', '/uploads/f2169d591601419d8ba1760d48a1b977.jpg', '4.2.2.6');
INSERT INTO "forcador_linhas" ("id", "fabricante_id", "nome", "versao_catalogo", "ativo_comercial", "observacao_versao", "linha_anterior_id", "descricao_comercial", "imagem_path", "id_comercial") VALUES (19, 2, 'EVIB AC - 8 Polos', '04/2024', TRUE, NULL, NULL, 'A linha de forçadores de ar EVIB da Mipal foi desenvolvida para aplicações em câmaras frigoríficas de baixa temperatura, onde a eficiência da troca térmica, a confiabilidade operacional e o controle preciso da temperatura são fatores determinantes para a conservação dos produtos armazenados. Projetada para operar com sistemas de degelo elétrico.', '/uploads/0402c985bbf14b36ba5cac7af08d1677.jpg', '4.2.2.7');