-- campo_sistema — bloco 1 de 1 (193 registros no total)

INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (1, 'T11', 1, 'Código Projeto', 'p_codigo_projeto', 0);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (2, 'T12', 1, 'Data', 'p_data', 1);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (3, 'T13', 1, 'Cliente', 'p_cliente', 2);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (4, 'T14', 1, 'Cidade de Instalação', 'p_cidade_instalacao', 3);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (5, 'T15', 1, 'Estado', 'p_estado_uf', 4);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (6, 'T16', 1, 'Altitude da Instalação (m)', 'p_altitude_m', 5);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (7, 'T17', 1, 'Estação Climatológica (INMET)', 'p_estacao_busca', 6);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (8, 'T18', 1, 'Temperatura Ambiente (°C)', 'p_temp_ambiente', 7);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (9, 'T19', 1, 'UR Externa (%)', 'p_ur_externa', 8);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (10, 'T110', 1, 'Contato', 'p_contato', 9);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (11, 'T111', 1, 'Telefone', 'p_telefone', 10);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (12, 'T112', 1, 'Tipo de Comando', 'p_tipo_comando', 11);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (13, 'T113', 1, 'Tensão Elétrica dos Equipamentos', 'p_tensao_equipamentos', 12);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (14, 'T114', 1, 'Tensão Elétrica de Comando', 'p_tensao_comando', 13);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (15, 'T115', 1, 'Custo de Energia (R$/kWh)', 'p_custo_energia', 14);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (16, 'T116', 1, 'Pasta de Salvamento do Projeto', 'p_pasta_salvamento', 15);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (17, 'T117', 1, 'Condição do Salão de Vendas', 'p_condicao_salao', 16);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (18, 'T118', 1, 'Considerar Iluminação Ambiente', 'p_considerar_iluminacao_ambiente', 17);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (19, 'T119', 1, 'Nome', 'sNome', 18);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (20, 'T120', 1, 'Gás Refrigerante', 'sGas', 19);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (21, 'T121', 1, 'Válvula de Expansão', 'sExp', 20);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (22, 'T122', 1, 'Fabricante Válvula', 'sFabricanteValvula', 21);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (23, 'T123', 1, 'Temp. Evaporação (°C)', 'sTempEvap', 22);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (24, 'T124', 1, 'Custo Sistema Simples (R$)', 'sCustoSistemaSimples', 23);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (25, 'T125', 1, 'Custo Sistema Projeto (R$)', 'sCustoSistemaProjeto', 24);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (26, 'T126', 1, 'Nº de Degelos/Dia', 'sQuantidadeDegeloDia', 25);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (27, 'T127', 1, 'Tempo de Degelo por Ciclo (min)', 'sTempoDegeloMin', 26);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (28, 'T128', 1, 'Tipo Automação Linhas', 'sTipoAutomacaoLinhas', 27);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (29, 'T129', 1, 'Fornecedor Automação Linhas', 'sAutomacaoLinhasFabricante', 28);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (30, 'T130', 1, 'Tipo de Equipamento Compressão', 'sTipoCompressao', 29);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (31, 'T131', 1, 'Estrutura', 'sEstruturaCompressao', 30);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (32, 'T132', 6, 'Seleção Condensador a Ar', 'sSelecaoCondensadorAr', 31);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (33, 'T133', 6, 'Delta de Condensação (°C)', 'sDeltaCondensacao', 32);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (34, 'T134', 1, 'Tipo de Partida - Compressores', 'sPartida', 33);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (35, 'T135', 1, 'Modo Operação - Compressores', 'sModoOperacao', 34);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (36, 'T136', 1, 'Tipo Automação Equipamentos', 'sAutomacao', 35);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (37, 'T137', 1, 'Fornecedor Automação Equipamentos', 'sAutomacaoFabricante', 36);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (38, 'T138', 1, 'Linha de Líquido — Temp. após Sub-resfriamento (°C)', 'sTempAposSubresfriamento', 37);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (39, 'T139', 1, 'Forçadores', 'p_fab_global_forcador', 38);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (40, 'T140', 1, 'Unidades Condensadoras', 'p_fab_global_uc', 39);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (41, 'T141', 1, 'Condensadores', 'p_fab_global_condensador', 40);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (42, 'T21', 2, 'Nome da Câmara', 'c2_nome', 41);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (43, 'T22', 2, 'Sistema (vínculo Tela 1)', 'c2_sistema_id', 42);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (44, 'T23', 2, 'Linha de Sucção', 'c2_linha_succao', 43);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (45, 'T24', 2, 'Linha Elétrica', 'c2_linha_eletrica', 44);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (46, 'T25', 2, 'Temp. Interna (°C)', 'c2_temp_interna', 45);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (47, 'T26', 2, 'Utilizar Válv. Reg. de Pressão?', 'c2_utilizar_valv_reg_pressao', 46);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (48, 'T27', 2, 'Dt. Evaporação Desejado (°C)', 'c2_dt_evaporacao_desejado', 47);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (49, 'T28', 2, 'Largura (m)', 'c2_largura', 48);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (50, 'T29', 2, 'Comprimento (m)', 'c2_comprimento', 49);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (51, 'T210', 2, 'Pé-Direito (m)', 'c2_pedireito', 50);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (52, 'T211', 2, 'Produto Estocado', 'c2_produto_id', 51);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (53, 'T212', 2, 'Qtd. Estocada (kg)', 'c2_qtd_estocada', 52);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (54, 'T213', 2, 'Movim. Diária (kg/24h)', 'c2_mov_diaria', 53);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (55, 'T214', 2, 'Tempo de Processo (h)', 'c2_tempo_processo', 54);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (56, 'T215', 2, 'Temp. Entrada (°C)', 'c2_temp_entrada', 55);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (57, 'T216', 2, 'Temp. Saída (°C)', 'c2_temp_saida', 56);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (58, 'T217', 2, 'Tipo de Embalagem', 'c2_tipo_embalagem_id', 57);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (59, 'T218', 2, 'Massa de Embalagem (kg/24h)', 'c2_massa_embalagem', 58);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (60, 'T219', 2, 'Isolamento Parede', 'c2_isolamento_parede_id', 59);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (61, 'T220', 2, 'Isolamento Teto', 'c2_isolamento_teto_id', 60);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (62, 'T221', 2, 'Isolamento Piso', 'c2_isolamento_piso_id', 61);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (63, 'T222', 2, 'Fonte do ar das paredes', 'c2_fonte_ar', 62);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (64, 'T223', 2, 'Temp. Adjacente Paredes (°C)', 'c2_temp_adjacente', 63);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (65, 'T224', 2, 'Umidade Adjacente Paredes (%)', 'c2_umidade_adjacente', 64);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (66, 'T225', 2, 'Qtd', 'c2_pt_qtd', 65);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (67, 'T226', 2, 'Largura (m)', 'c2_pt_larg', 66);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (68, 'T227', 2, 'Altura (m)', 'c2_pt_alt', 67);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (69, 'T228', 2, 'Abertura (min/h)', 'c2_pt_freq', 68);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (70, 'T229', 2, 'Proteção', 'c2_pt_protecao', 69);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (71, 'T230', 2, 'Fonte do ar', 'c2_pt_fonte', 70);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (72, 'T231', 2, 'Temp. Adjacente da porta (°C)', 'c2_pt_temp', 71);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (73, 'T232', 2, 'Umidade Adjacente da porta (%)', 'c2_pt_ur', 72);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (74, 'T233', 2, 'Nº Pessoas', 'c2_num_pessoas', 73);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (75, 'T234', 2, 'Tempo (h/24h)', 'c2_tempo_pessoas', 74);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (76, 'T235', 2, 'Qtd. Luminárias', 'c2_qtd_luminarias', 75);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (77, 'T236', 2, 'Horas Iluminação/Dia (carga)', 'c2_horas_iluminacao_carga', 77);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (78, 'T237', 2, 'Tipo (catálogo)', 'c2_eqTipo', 78);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (79, 'T238', 2, 'Qtd.', 'c2_eqQtd', 79);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (80, 'T239', 2, 'Tempo (h/24h)', 'c2_eqTempo', 80);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (81, 'T240', 2, 'Fator de Segurança (%)', 'c2_fator_seguranca', 81);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (82, 'T241', 2, 'Tempo Func. Compressores (h/24h)', 'c2_tempo_func_compressores', 82);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (83, 'T242', 2, 'Fabricante', 'c2_evFab', 83);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (84, 'T243', 2, 'Linha', 'c2_evLinha', 84);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (85, 'T31', 3, 'Nome da Câmara', 'c3_nome', 85);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (86, 'T32', 3, 'Sistema (vínculo Tela 1)', 'c3_sistema_id', 86);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (87, 'T33', 3, 'Linha de Sucção', 'c3_linha_succao', 87);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (88, 'T34', 3, 'Linha Elétrica', 'c3_linha_eletrica', 88);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (89, 'T35', 3, 'Tipo', 'c3_tabela02_id', 89);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (90, 'T36', 3, 'Área (m²)', 'c3_area', 90);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (91, 'T37', 3, 'Pé-Direito (m)', 'c3_pedireito', 91);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (92, 'T38', 3, 'Temp. Interna (°C)', 'c3_temp_interna', 92);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (93, 'T39', 3, 'Utilizar Válv. Reg. de Pressão?', 'c3_utilizar_valv_reg_pressao', 93);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (94, 'T310', 3, 'Dt. Evaporação Desejado (°C)', 'c3_dt_evaporacao_desejado', 94);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (95, 'T311', 3, 'Nº de Portas', 'c3_num_portas', 95);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (96, 'T312', 3, 'Largura do Vão (m)', 'c3_porta_largura', 96);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (97, 'T313', 3, 'Altura do Vão (m)', 'c3_porta_altura', 97);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (98, 'T314', 3, 'Fator de Segurança (%)', 'c3_fator_seguranca', 98);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (99, 'T315', 3, 'Fabricante', 'c3_evFab', 99);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (100, 'T316', 3, 'Linha', 'c3_evLinha', 100);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (101, 'T41', 4, 'Sistema (vínculo Tela 1)', 'c4_sistema_id', 101);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (102, 'T42', 4, 'Linha de Sucção', 'c4_linha_succao', 102);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (103, 'T43', 4, 'Linha Elétrica', 'c4_linha_eletrica', 103);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (104, 'T44', 4, 'Setor', 'c4_setor_id', 104);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (105, 'T45', 4, 'Banco de Dados', 'c4_banco_id', 105);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (106, 'T46', 4, 'Modelo', 'c4_modelo_expositor_id', 106);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (107, 'T47', 4, 'Comprimento do Módulo (m)', 'c4_modCompr', 107);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (108, 'T48', 4, 'Quantidade', 'c4_modQtd', 108);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (109, 'T51', 5, 'Fator de Potência', 't5_fatorPotencia', 109);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (110, 'T52', 5, 'Fonte Tensão Quadro de Linhas', 't5_quadroTensaoFonte', 110);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (111, 'T53', 5, 'Observações Técnicas', 't5_observacao', 111);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (112, 'T61', 6, 'Sistema (Rack Paralelo)', 't11_sistema_id', 112);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (113, 'T62', 6, 'Fabricante Compressor', 't11_fabricante_compressor', 113);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (114, 'T63', 6, 'Linha Compressor', 't11_linha_compressor', 114);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (115, 'T64', 6, 'Quantidade de Compressores/Rack', 't11_quantidade_compressores', 115);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (116, 'T65', 6, 'Folga Técnica (%)', 't11_folga_tecnica_pct', 116);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (117, 'T66', 6, 'Tipo Motor Compress.', 't11_filtro_motor_compressor', 117);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (118, 'T67', 6, 'Fabricante Condensador', 't11_cond_fabricante', 118);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (119, 'T68', 6, 'Linha Condensador', 't11_cond_linha', 119);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (120, 'T69', 6, 'Tipo Condensador', 't11_cond_tipoCondensador', 120);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (121, 'T610', 6, 'Tipo de Motor', 't11_cond_polos', 121);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (122, 'T611', 6, 'Aletas por Polegada (FPI)', 't11_cond_fpi', 122);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (123, 'T612', 6, 'Proteção de Aletas', 't11_cond_protecaoAletas', 123);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (124, 'T613', 6, 'Folga Condensador (%)', 't11_cond_folga', 124);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (125, 'T614', 6, 'Quantidade de Condensadores', 't11_cond_qtdCondensadores', 125);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (126, 'T615', 6, 'Notas', 't11_cond_notas', 126);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (127, 'T71', 7, 'Largura da Placa (Parede/Teto) (m)', 't10_largPlaca', 127);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (128, 'T72', 7, 'Largura da Placa de Piso (m)', 't10_pisoLarg', 128);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (129, 'T73', 7, 'Comprimento da Placa de Piso (m)', 't10_pisoComp', 129);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (130, 'T74', 7, 'Largura Mín. de Aproveitamento (m)', 't10_larguraMinAprov', 130);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (131, 'T244', 2, 'Portas — Qtd', 'porta_quantidade', 131);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (132, 'T245', 2, 'Portas — Largura (m)', 'porta_largura', 132);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (133, 'T246', 2, 'Portas — Altura (m)', 'porta_altura', 133);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (134, 'T247', 2, 'Portas — Abertura (min/h)', 'porta_freq_abertura_min_h', 134);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (135, 'T248', 2, 'Portas — Proteção', 'porta_protecao', 135);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (136, 'T249', 2, 'Portas — Fonte do ar', 'porta_fonte_ar', 136);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (137, 'T250', 2, 'Portas — Temp. Adjacente (°C)', 'porta_temp_adjacente', 137);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (138, 'T251', 2, 'Portas — Umidade Adjacente (%)', 'porta_umidade_adjacente', 138);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (139, 'T252', 2, 'Forçadores — Folga Desejada (%)', 'forcador_folga', 139);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (140, 'T253', 2, 'Forçadores — Qtd.', 'forcador_quantidade', 140);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (141, 'T254', 2, 'Forçadores — Considerar', 'forcador_considerar', 141);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (142, 'T255', 2, 'Forçadores — Tipo de Degelo', 'forcador_tipo_degelo', 142);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (143, 'T256', 2, 'Válvula — Modelo', 'valvula_modelo', 143);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (144, 'T257', 2, 'Válvula — Orifício', 'valvula_orificio', 144);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (145, 'T258', 2, 'Válvula — Capacidade Unit. (kcal/h)', 'valvula_capacidade', 145);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (146, 'T259', 2, 'Válvula — Conexão Entrada', 'valvula_entrada', 146);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (147, 'T260', 2, 'Válvula — Conexão Saída', 'valvula_saida', 147);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (148, 'T261', 2, 'Válvula — Tensão', 'valvula_tensao', 148);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (149, 'T262', 2, 'Válvula — Tipo (motor)', 'valvula_tipomotor', 149);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (150, 'T263', 2, 'Válvula — Controlador', 'valvula_controlador', 150);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (151, 'T317', 3, 'Forçadores — Folga Desejada (%)', 'forcador_folga', 151);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (152, 'T318', 3, 'Forçadores — Qtd.', 'forcador_quantidade', 152);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (153, 'T319', 3, 'Forçadores — Considerar', 'forcador_considerar', 153);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (154, 'T320', 3, 'Forçadores — Tipo de Degelo', 'forcador_tipo_degelo', 154);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (155, 'T321', 3, 'Válvula — Modelo', 'valvula_modelo', 155);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (156, 'T322', 3, 'Válvula — Orifício', 'valvula_orificio', 156);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (157, 'T323', 3, 'Válvula — Capacidade Unit. (kcal/h)', 'valvula_capacidade', 157);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (158, 'T324', 3, 'Válvula — Conexão Entrada', 'valvula_entrada', 158);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (159, 'T325', 3, 'Válvula — Conexão Saída', 'valvula_saida', 159);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (160, 'T326', 3, 'Válvula — Tensão', 'valvula_tensao', 160);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (161, 'T327', 3, 'Válvula — Tipo (motor)', 'valvula_tipomotor', 161);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (162, 'T328', 3, 'Válvula — Controlador', 'valvula_controlador', 162);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (163, 'T616', 6, 'Materiais Rack — Modelo', 'mat_modelo', 163);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (164, 'T617', 6, 'Materiais Rack — Quantidade', 'mat_qtd', 164);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (165, 'T142', 1, 'Modelo Controlador Linhas', 'sModeloControladorLinhas', 182);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (166, 'T143', 1, 'Modelo Controlador Equipamentos', 'sModeloControladorEquipamentos', 183);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (167, 'T264', 2, 'Iluminação — Tipo Ambiente', 'c2_tipo_ambiente_lumino_id', 184);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (168, 'T265', 2, 'Iluminação — Modelo Luminária', 'c2_modelo_luminaria_texto', 185);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (169, 'T266', 2, 'Iluminação — Potência/Luminária (W)', 'c2_potencia_luminaria_texto', 192);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (170, 'T329', 3, 'Largura (m)', 'c3_largura', 186);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (171, 'T330', 3, 'Comprimento (m)', 'c3_comprimento', 187);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (172, 'T331', 3, 'Iluminação — Qtd. Luminárias', 'c3_qtd_luminarias', 188);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (173, 'T332', 3, 'Iluminação — Tipo Ambiente', 'c3_tipo_ambiente_lumino_id', 189);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (174, 'T333', 3, 'Iluminação — Horas Iluminação/Dia (carga)', 'c3_horas_iluminacao_carga', 190);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (175, 'T334', 3, 'Iluminação — Modelo Luminária', 'c3_modelo_luminaria_texto', 191);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (176, 'T335', 3, 'Iluminação — Potência/Luminária (W)', 'c3_potencia_luminaria_texto', 193);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (177, 'T75', 7, 'Painéis — Câmara', 'painel_camara', 165);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (178, 'T76', 7, 'Painéis — Nome do Ambiente (se não climatizado)', 'painel_ambiente_nome', 166);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (179, 'T77', 7, 'Painéis — Tipo', 'painel_tipo', 167);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (180, 'T78', 7, 'Painéis — Espessura', 'painel_espessura', 168);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (181, 'T79', 7, 'Painéis — Perímetro/Largura (m)', 'painel_dimensao_1', 169);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (182, 'T710', 7, 'Painéis — Altura/Comprimento (m)', 'painel_dimensao_2', 170);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (183, 'T711', 7, 'Portas — Câmara', 'porta_camara', 171);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (184, 'T712', 7, 'Portas — Nome do Ambiente (se não climatizado)', 'porta_ambiente_nome', 172);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (185, 'T713', 7, 'Portas — Função', 'porta_funcao', 173);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (186, 'T714', 7, 'Portas — Modelo', 'porta_modelo', 174);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (187, 'T715', 7, 'Portas — Sentido', 'porta_sentido', 175);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (188, 'T716', 7, 'Portas — Vão Largura (mm)', 'porta_vao_largura_mm', 176);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (189, 'T717', 7, 'Portas — Vão Altura (mm)', 'porta_vao_altura_mm', 177);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (190, 'T718', 7, 'Portas — Fixação', 'porta_fixacao', 178);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (191, 'T719', 7, 'Portas — Esp. Fixação (mm)', 'porta_espessura_fixacao_mm', 179);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (192, 'T720', 7, 'Portas — Tensão', 'porta_tensao', 180);
INSERT INTO "campo_sistema" ("id", "campo_id", "tela", "rotulo", "seletor_html", "ordem") VALUES (193, 'T721', 7, 'Portas — Observações', 'porta_observacoes', 181);